namespace PigeDiary {
  type Row=PigeAPI.Row;
  type Diary=Row&{class_group_id:string;academic_year_id:string;component_id:string;teacher_assignment_id?:string|null;version:number;status:string;class_name:string;component_name:string;year_name:string;teacher_name:string;lessons?:Lesson[];roster?:Roster[]};
  type Lesson=Row&{lesson_date:string;lesson_count:number;content:string;academic_period_id?:string|null;skills:string;methodology:string;activities:string;homework:string;notes:string};
  type Roster={enrollment_id:string;student_id:string;number:string;name:string;enrollment_status:string;attendance?:{status:string;note:string}|null};
  type AssessmentResult={id?:string;version?:number;numeric_score:string|number|null;concept:string;note:string};
  type CommunicationRecipient={guardian_link_id:string;name:string;relationship:string;portal_account_count:number};
  type Props={schoolId:string;permissions:string[]};
  const today=()=>new Date().toISOString().slice(0,10);
  export const component={props:['schoolId','permissions'],render:PigeRenders.diary,setup(props:Props){
    const state=Vue.reactive({
      busy:false,error:'',notice:'',tab:'diaries',
      diaries:[] as Diary[],selected:null as Diary|null,periods:[] as Row[],components:[] as Row[],groups:[] as Row[],assignments:[] as Row[],plans:[] as Row[],
      periodForm:{academic_year_id:'',name:'',starts_on:'',ends_on:'',order_index:1,active:true},
      componentForm:{name:'',code:'',workload_hours:0,active:true},
      diaryForm:{class_group_id:'',component_id:'',teacher_assignment_id:'',notes:''},
      planForm:{class_group_id:'',component_id:'',academic_period_id:'',teacher_assignment_id:'',objectives:'',thematic_units:'',knowledge_objects:'',bncc_references:'',methodology:'',resources:'',assessment_strategy:'',notes:'',status:'draft'},
      lessonForm:{academic_period_id:'',lesson_date:today(),lesson_count:1,content:'',skills:'',methodology:'',activities:'',homework:'',notes:''},
      selectedLesson:null as Lesson|null,attendance:[] as Roster[],
      assessments:[] as Row[],selectedAssessment:null as Row|null,assessmentRoster:[] as (Roster&{result?:AssessmentResult|null})[],
      assessmentForm:{academic_period_id:'',title:'',kind:'activity',assessment_date:today(),value_type:'numeric',max_score:'10',weight:'1',description:'',skills:'',status:'draft'},
      opinions:[] as Row[],opinionForm:{academic_period_id:'',enrollment_id:'',text:'',status:'draft'},
      pedagogicalRecords:[] as Row[],pedagogicalForm:{enrollment_id:'',record_date:today(),kind:'observation',text:''},
      closePeriod:'',closeReason:'Fechamento pedagógico conferido.',reopenReason:'',
      summary:null as null|{lessons:number;lesson_count:number;attendance_records:number;absences:number;justified_absences:number;roster:number;assessments?:number;opinions?:number;pedagogical_records?:number},
      history:{closures:[] as Row[],revisions:[] as Row[]},
      dashboard:{items:[] as Row[],totals:{} as Row},
      assessmentRules:[] as Row[],
      assessmentRuleForm:{period_id:'',method:'arithmetic',scale_max:'10',decimal_places:2,minimum_score:'',minimum_attendance_percent:'',justified_absence_counts_as_present:'',recovery_mode:'none',concept_scale:'',required_opinion:false,version:null as number|null},
      periodResults:[] as Row[],
      occurrences:[] as Row[],
      communicationRecipients:[] as CommunicationRecipient[],communications:[] as Row[],
      communicationForm:{enrollment_id:'',academic_period_id:'',occurrence_id:'',recipient_guardian_link_ids:[] as string[],title:'',message:'',client_key:PigeOnline.newId()},
      occurrenceForm:{academic_period_id:'',enrollment_id:'',occurrence_date:today(),kind:'pedagogical',title:'',description:'',status:'draft'},
      reportType:'class_diary',reportPeriod:'',reportEnrollment:''
    });
    const base=()=>'/schools/'+props.schoolId;
    const can=(p:string)=>props.permissions.includes(p);
    const str=(v:unknown)=>v==null?'':String(v);
    const date=(v:unknown)=>{const x=str(v);return x?new Intl.DateTimeFormat('pt-BR',{timeZone:'UTC'}).format(new Date(x.length===10?x+'T12:00:00Z':x)):'—';};
    const labels:Record<string,string>={open:'Aberto',draft:'Rascunho',submitted:'Enviado',reviewed:'Revisado',closed:'Fechado',present:'Presente',absent:'Falta',justified_absence:'Falta justificada',active:'Ativo',suspended:'Suspenso'};
    const label=(v:unknown)=>labels[str(v)]||str(v)||'—';
    async function run(action:()=>Promise<void>){if(state.busy)return;state.busy=true;state.error='';state.notice='';try{await action();}catch(e){state.error=e instanceof Error?e.message:String(e);}finally{state.busy=false;}}
    async function loadBase(){const results=await Promise.all([
      PigeAPI.request<Diary[]>(base()+'/diaries'),
      PigeAPI.request<Row[]>(base()+'/academic-periods'),
      PigeAPI.request<Row[]>(base()+'/curriculum-components'),
      PigeAPI.request<Row[]>(base()+'/class-groups').catch(()=>[] as Row[]),
      PigeAPI.request<Row[]>(base()+'/teacher-assignments').catch(()=>[] as Row[]),
      PigeAPI.request<any>(base()+'/diary-dashboard').catch(()=>({items:[],totals:{}}))
    ]);state.diaries=results[0] as Diary[];state.periods=results[1] as Row[];state.components=results[2] as Row[];state.groups=results[3] as Row[];state.assignments=results[4] as Row[];state.dashboard=results[5] as {items:Row[];totals:Row};
      if(!state.periodForm.academic_year_id&&state.groups.length)state.periodForm.academic_year_id=str(state.groups[0].academic_year_id);
    }
    async function load(){await run(loadBase);}
    async function selectDiary(d:Diary){await run(async()=>{state.selected=await PigeAPI.request<Diary>(base()+'/diaries/'+d.id);state.summary=await PigeAPI.request<any>(base()+'/diaries/'+d.id+'/summary');state.history=await PigeAPI.request<any>(base()+'/diaries/'+d.id+'/history');state.plans=await PigeAPI.request<Row[]>(base()+'/curriculum-plans?class_group_id='+encodeURIComponent(d.class_group_id)+'&component_id='+encodeURIComponent(d.component_id));state.selectedLesson=null;state.attendance=[];state.selectedAssessment=null;state.assessmentRoster=[];state.planForm.class_group_id=d.class_group_id;state.planForm.component_id=d.component_id;state.planForm.teacher_assignment_id=d.teacher_assignment_id||'';state.assessments=await PigeAPI.request<Row[]>(base()+'/diaries/'+d.id+'/assessments');state.assessmentRules=await PigeAPI.request<Row[]>(base()+'/diaries/'+d.id+'/assessment-rules');state.periodResults=[];state.occurrences=await PigeAPI.request<Row[]>(base()+'/diaries/'+d.id+'/occurrences');state.occurrenceForm={academic_period_id:'',enrollment_id:'',occurrence_date:today(),kind:'pedagogical',title:'',description:'',status:'draft'};const firstPeriod=state.periods.find(p=>p.academic_year_id===d.academic_year_id);if(firstPeriod)selectRulePeriod(str(firstPeriod.id));state.opinions=await PigeAPI.request<Row[]>(base()+'/diaries/'+d.id+'/opinions');state.pedagogicalRecords=await PigeAPI.request<Row[]>(base()+'/diaries/'+d.id+'/pedagogical-records');state.communications=await PigeAPI.request<Row[]>(base()+'/diaries/'+d.id+'/communications');state.communicationRecipients=[];state.communicationForm={enrollment_id:'',academic_period_id:'',occurrence_id:'',recipient_guardian_link_ids:[],title:'',message:'',client_key:PigeOnline.newId()};});}
    function selectRulePeriod(periodId:string){const rule=state.assessmentRules.find(x=>x.academic_period_id===periodId);state.assessmentRuleForm={period_id:periodId,method:str(rule?.method)||'arithmetic',scale_max:str(rule?.scale_max)||'10',decimal_places:Number(rule?.decimal_places??2),minimum_score:str(rule?.minimum_score),minimum_attendance_percent:str(rule?.minimum_attendance_percent),justified_absence_counts_as_present:rule?.justified_absence_counts_as_present==null?'':String(rule.justified_absence_counts_as_present),recovery_mode:str(rule?.recovery_mode)||'none',concept_scale:Array.isArray(rule?.concept_scale)?rule.concept_scale.join(', '):'',required_opinion:Boolean(rule?.required_opinion),version:rule?.version==null?null:Number(rule.version)};}
    async function saveAssessmentRule(){if(!state.selected||!state.assessmentRuleForm.period_id)return;await run(async()=>{const f=state.assessmentRuleForm;const body={method:f.method,scale_max:f.scale_max,decimal_places:f.decimal_places,minimum_score:f.minimum_score||null,minimum_attendance_percent:f.minimum_attendance_percent||null,justified_absence_counts_as_present:f.minimum_attendance_percent?(f.justified_absence_counts_as_present==='true'):null,recovery_mode:f.recovery_mode,concept_scale:f.method==='concept'?f.concept_scale.split(/[,;]+/).map(x=>x.trim()).filter(Boolean):[],required_opinion:f.required_opinion,version:f.version};const saved=await PigeAPI.request<Row>(base()+'/diaries/'+state.selected!.id+'/assessment-rules/'+f.period_id,{method:'PUT',body:JSON.stringify(body)});state.assessmentRules=state.assessmentRules.filter(x=>x.academic_period_id!==f.period_id).concat(saved);selectRulePeriod(f.period_id);state.notice='Regra salva; os resultados mudam apenas após consolidação explícita.';});}
    async function loadPeriodResults(){if(!state.selected||!state.assessmentRuleForm.period_id)return;await run(async()=>{const r=await PigeAPI.request<{items:Row[]}>(base()+'/diaries/'+state.selected!.id+'/periods/'+state.assessmentRuleForm.period_id+'/results');state.periodResults=r.items;});}
    async function consolidatePeriod(){if(!state.selected||!state.assessmentRuleForm.period_id)return;await run(async()=>{const r=await PigeAPI.post<{results:Row[];pending:number}>(base()+'/diaries/'+state.selected!.id+'/periods/'+state.assessmentRuleForm.period_id+'/consolidate',{version:state.selected!.version});state.periodResults=r.results;state.notice='Consolidação auditada; '+r.pending+' resultado(s) pendente(s).';await loadBase();});}
    async function saveOccurrence(){if(!state.selected)return;await run(async()=>{const f=state.occurrenceForm;await PigeAPI.post(base()+'/diaries/'+state.selected!.id+'/occurrences',{...f,academic_period_id:f.academic_period_id||null});state.occurrences=await PigeAPI.request<Row[]>(base()+'/diaries/'+state.selected!.id+'/occurrences');state.occurrenceForm={academic_period_id:f.academic_period_id,enrollment_id:'',occurrence_date:today(),kind:'pedagogical',title:'',description:'',status:'draft'};state.notice='Ocorrência registrada no Diário.';});}
    async function loadCommunicationRecipients(){if(!state.selected||!state.communicationForm.enrollment_id){state.communicationRecipients=[];state.communicationForm.recipient_guardian_link_ids=[];return;}const query='?enrollment_id='+encodeURIComponent(state.communicationForm.enrollment_id);state.communicationRecipients=await PigeAPI.request<CommunicationRecipient[]>(base()+'/diaries/'+state.selected.id+'/communication-recipients'+query);state.communicationForm.recipient_guardian_link_ids=[];}
    function communicationOccurrenceChanged(){const occurrence=state.occurrences.find(x=>x.id===state.communicationForm.occurrence_id);if(occurrence?.academic_period_id)state.communicationForm.academic_period_id=str(occurrence.academic_period_id);}
    async function sendCommunication(){if(!state.selected)return;await run(async()=>{const f=state.communicationForm;const result=await PigeAPI.post<{created:number;messages:Row[];channel:string}>(base()+'/diaries/'+state.selected!.id+'/communications',{...f,academic_period_id:f.academic_period_id||null,occurrence_id:f.occurrence_id||null});state.communications=await PigeAPI.request<Row[]>(base()+'/diaries/'+state.selected!.id+'/communications');state.communicationForm={...f,occurrence_id:'',recipient_guardian_link_ids:[],title:'',message:'',client_key:PigeOnline.newId()};state.communicationRecipients=[];state.notice=result.created?'Comunicado disponibilizado no portal para '+result.created+' conta(s).':'Esta operação já havia sido processada; nenhum comunicado duplicado foi criado.';});}
    async function createPeriod(){await run(async()=>{await PigeAPI.post(base()+'/academic-periods',state.periodForm);state.periodForm={academic_year_id:state.periodForm.academic_year_id,name:'',starts_on:'',ends_on:'',order_index:state.periodForm.order_index+1,active:true};await loadBase();state.notice='Período letivo criado.';});}
    async function createComponent(){await run(async()=>{await PigeAPI.post(base()+'/curriculum-components',state.componentForm);state.componentForm={name:'',code:'',workload_hours:0,active:true};await loadBase();state.notice='Componente curricular criado.';});}
    async function createDiary(){await run(async()=>{const body={...state.diaryForm,teacher_assignment_id:state.diaryForm.teacher_assignment_id||null};const d=await PigeAPI.post<Diary>(base()+'/diaries',body);state.diaryForm={class_group_id:'',component_id:'',teacher_assignment_id:'',notes:''};await loadBase();await selectDiary(d);state.notice='Diário aberto.';});}
    async function createPlan(){if(!state.selected)return;await run(async()=>{const f=state.planForm;await PigeAPI.post(base()+'/curriculum-plans',{...f,academic_period_id:f.academic_period_id||null,teacher_assignment_id:f.teacher_assignment_id||null,bncc_references:f.bncc_references.split(/[\s,;]+/).map(x=>x.trim()).filter(Boolean)});state.plans=await PigeAPI.request<Row[]>(base()+'/curriculum-plans?class_group_id='+encodeURIComponent(state.selected!.class_group_id)+'&component_id='+encodeURIComponent(state.selected!.component_id));state.notice='Planejamento registrado.';});}
    async function createLesson(){if(!state.selected)return;await run(async()=>{await PigeAPI.post(base()+'/diaries/'+state.selected!.id+'/lessons',{...state.lessonForm,academic_period_id:state.lessonForm.academic_period_id||null});state.lessonForm={academic_period_id:state.lessonForm.academic_period_id,lesson_date:today(),lesson_count:1,content:'',skills:'',methodology:'',activities:'',homework:'',notes:''};await selectDiary(state.selected!);state.notice='Aula registrada.';});}
    async function openAttendance(lesson:Lesson){if(!state.selected)return;await run(async()=>{const result=await PigeAPI.request<{lesson:Lesson;roster:Roster[]}>(base()+'/diaries/'+state.selected!.id+'/lessons/'+lesson.id+'/attendance');state.selectedLesson=result.lesson;state.attendance=result.roster.map(r=>({...r,attendance:r.attendance||{status:'present',note:''}}));});}
    async function saveAttendance(){if(!state.selected||!state.selectedLesson)return;await run(async()=>{await PigeAPI.request(base()+'/diaries/'+state.selected!.id+'/lessons/'+state.selectedLesson!.id+'/attendance',{method:'PUT',body:JSON.stringify({items:state.attendance.map(r=>({enrollment_id:r.enrollment_id,status:r.attendance?.status||'present',note:r.attendance?.note||''}))})});state.notice='Chamada salva.';await selectDiary(state.selected!);});}
    async function createAssessment(){if(!state.selected)return;await run(async()=>{const f=state.assessmentForm;await PigeAPI.post(base()+'/diaries/'+state.selected!.id+'/assessments',{...f,academic_period_id:f.academic_period_id||null,max_score:f.value_type==='numeric'?(f.max_score||null):null,weight:f.weight||null});state.assessmentForm={academic_period_id:f.academic_period_id,title:'',kind:'activity',assessment_date:today(),value_type:f.value_type,max_score:'10',weight:'1',description:'',skills:'',status:'draft'};state.assessments=await PigeAPI.request<Row[]>(base()+'/diaries/'+state.selected!.id+'/assessments');state.notice='Avaliação criada.';});}
    async function openAssessment(a:Row){if(!state.selected)return;await run(async()=>{const result=await PigeAPI.request<{instrument:Row;roster:(Roster&{result?:AssessmentResult|null})[]}>(base()+'/diaries/'+state.selected!.id+'/assessments/'+a.id+'/results');state.selectedAssessment=result.instrument;state.assessmentRoster=result.roster.map(r=>({...r,result:r.result||{numeric_score:null,concept:'',note:''}}));});}
    async function saveAssessmentResults(){if(!state.selected||!state.selectedAssessment)return;await run(async()=>{await PigeAPI.request(base()+'/diaries/'+state.selected!.id+'/assessments/'+state.selectedAssessment!.id+'/results',{method:'PUT',body:JSON.stringify({items:state.assessmentRoster.map(r=>({enrollment_id:r.enrollment_id,numeric_score:state.selectedAssessment!.value_type==='numeric'?(r.result?.numeric_score??null):null,concept:state.selectedAssessment!.value_type==='concept'?str(r.result?.concept):'',note:str(r.result?.note)}))})});state.notice='Resultados salvos.';await selectDiary(state.selected!);});}
    async function saveOpinion(){if(!state.selected)return;await run(async()=>{await PigeAPI.post(base()+'/diaries/'+state.selected!.id+'/opinions',{...state.opinionForm,academic_period_id:state.opinionForm.academic_period_id||null});state.opinionForm={academic_period_id:state.opinionForm.academic_period_id,enrollment_id:'',text:'',status:'draft'};state.opinions=await PigeAPI.request<Row[]>(base()+'/diaries/'+state.selected!.id+'/opinions');state.notice='Parecer salvo.';});}
    async function createPedagogicalRecord(){if(!state.selected)return;await run(async()=>{await PigeAPI.post(base()+'/diaries/'+state.selected!.id+'/pedagogical-records',state.pedagogicalForm);state.pedagogicalForm={enrollment_id:'',record_date:today(),kind:'observation',text:''};state.pedagogicalRecords=await PigeAPI.request<Row[]>(base()+'/diaries/'+state.selected!.id+'/pedagogical-records');state.notice='Registro pedagógico incluído.';});}
    async function submitDiary(){if(!state.selected)return;await run(async()=>{await PigeAPI.post(base()+'/diaries/'+state.selected!.id+'/submit',{version:state.selected!.version});await selectDiary(state.selected!);state.notice='Diário enviado para revisão.';});}
    async function reviewDiary(){if(!state.selected)return;await run(async()=>{await PigeAPI.post(base()+'/diaries/'+state.selected!.id+'/review',{version:state.selected!.version});await selectDiary(state.selected!);state.notice='Diário marcado como revisado.';});}
    async function closeDiary(){if(!state.selected)return;await run(async()=>{const period=Boolean(state.closePeriod);await PigeAPI.post(base()+'/diaries/'+state.selected!.id+'/close',{academic_period_id:state.closePeriod||null,reason:state.closeReason,version:state.selected!.version});await selectDiary(state.selected!);state.notice=period?'Período fechado com snapshot e hash de integridade.':'Diário fechado com snapshot e hash de integridade.';});}
    async function reopenDiary(){if(!state.selected)return;await run(async()=>{await PigeAPI.post(base()+'/diaries/'+state.selected!.id+'/reopen',{reason:state.reopenReason,version:state.selected!.version});state.reopenReason='';await selectDiary(state.selected!);state.notice='Diário reaberto com registro de retificação.';});}
    async function report(){if(state.selected)await run(()=>{const q=new URLSearchParams();if(state.reportPeriod)q.set('academic_period_id',state.reportPeriod);if(state.reportType==='student_record'&&state.reportEnrollment)q.set('enrollment_id',state.reportEnrollment);const query=q.toString();return PigeAPI.download(base()+'/diaries/'+state.selected!.id+'/reports/'+state.reportType+'.pdf'+(query?'?'+query:''),'diario-'+state.reportType+'.pdf');});}
    Vue.onMounted(()=>{void load();});
    return{state,can,str,date,label,load,selectDiary,loadCommunicationRecipients,communicationOccurrenceChanged,sendCommunication,createPeriod,createComponent,createDiary,createPlan,createLesson,openAttendance,saveAttendance,createAssessment,openAssessment,saveAssessmentResults,saveOpinion,createPedagogicalRecord,submitDiary,reviewDiary,closeDiary,reopenDiary,report,selectRulePeriod,saveAssessmentRule,loadPeriodResults,consolidatePeriod,saveOccurrence};
  }};
}
