/** Caixa institucional: o conteúdo recebido é sempre apresentado como texto. */
namespace PigeEmail {
  type Folder={id:string;name:string;role:string;total:number;unread:number};
  type Account={available:boolean;connected:boolean;address:string;display_name:string;needs_password:boolean;limits?:{message_bytes:number;attachment_bytes:number;recipients:number};connection_parameters?:unknown};
  type Attachment={part:string;filename:string;content_type:string;size:number};
  type Message={uid:number;uidvalidity:number;subject:string;from:string;to:string;cc?:string;bcc?:string;date:string;seen:boolean;flagged:boolean;size:number;text?:string;message_id?:string;in_reply_to?:string;attachments?:Attachment[]};
  type Page={items:Message[];folder:string;uidvalidity:number;next_before_uid:number|null};
  type Draft={folder:string;uid:number;uidvalidity:number};
  type Upload={filename:string;content_type:string;content_base64:string;size:number};
  type Compose={to:string;cc:string;bcc:string;subject:string;text:string;attachments:Upload[];in_reply_to:string;draft:Draft|null};
  type SendResult={status:'sent'|'partial'|'failed'|'uncertain'|'sending';message_id:string;sent_saved:boolean;refused:string[];message:string};
  const empty=():Compose=>({to:'',cc:'',bcc:'',subject:'',text:'',attachments:[],in_reply_to:'',draft:null});
  const roles:Record<string,string>={inbox:'Caixa de entrada',sent:'Enviados',drafts:'Rascunhos',spam:'Spam',trash:'Lixeira',archive:'Arquivo'};
  const symbols:Record<string,string>={inbox:'inbox',sent:'send',drafts:'file-text',spam:'shield-alert',trash:'trash-2',archive:'archive'};
  function date(value:string,full=false):string {const d=new Date(value);return Number.isNaN(d.getTime())?'Data indisponível':new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short',...(full?{year:'numeric' as const}:{}),hour:'2-digit',minute:'2-digit'}).format(d);}
  function size(value:number):string{return value<1024?value+' B':value<1048576?(value/1024).toFixed(0)+' KB':(value/1048576).toFixed(1)+' MB';}
  function addresses(value:string):string[]{return value.split(/[,;\n]/).map(x=>x.trim()).filter(Boolean).map(x=>x.match(/<([^<>]+)>/)?.[1]||x);}
  function headerAddresses(value:string|undefined):string{return (value||'').match(/[A-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi)?.join(', ')||'';}
  function base64(bytes:Uint8Array):string{let text='';for(let i=0;i<bytes.length;i+=32768)text+=String.fromCharCode(...bytes.subarray(i,i+32768));return btoa(text);}
  let unsavedWork=()=>false;
  export function hasUnsavedWork():boolean{return unsavedWork();}
  export const component={props:['schoolId','admin'],render:PigeRenders.email,setup(props:{schoolId:string;admin?:boolean}){
    const s=Vue.reactive({busy:false,loading:true,error:'',notice:'',account:null as Account|null,password:'',folders:[] as Folder[],folder:'',items:[] as Message[],selected:null as Message|null,q:'',activeQuery:'',next:null as number|null,cursors:[] as (number|null)[],cursor:null as number|null,showFolders:false,showConnection:false,showSettings:false,settings:{imap_host:'',smtp_host:'',smtp_port:465},newFolder:'',showNewFolder:false,folderEdit:false,folderRename:'',folderDeleteConfirm:false,moveTo:'',deleteConfirm:false,disconnectConfirm:false,compose:null as Compose|null,composeInitial:'',showCopies:false,discard:false,composeError:'',composeNotice:'',sendId:'',pendingPayload:null as Record<string,unknown>|null,sendResult:null as SendResult|null});
    const base=()=>'/schools/'+props.schoolId+'/email';
    const folder=()=>s.folders.find(x=>x.id===s.folder);
    const folderName=(item:Folder)=>roles[item.role]||item.name;
    const folderIcon=(item:Folder)=>symbols[item.role]||'folder';
    const query=(message:Message,folderId=s.folder)=>new URLSearchParams({folder:folderId,uidvalidity:String(message.uidvalidity)}).toString();
    const messagePath=(message:Message)=>base()+'/messages/'+message.uid;
    const dirty=()=>Boolean(s.compose&&JSON.stringify(s.compose)!==s.composeInitial);
    async function run(action:()=>Promise<void>):Promise<void>{if(s.busy)return;s.busy=true;s.error='';s.notice='';try{await action();}catch(error){s.error=error instanceof Error?error.message:'Não foi possível concluir a operação.';}finally{s.busy=false;s.loading=false;}}
    async function loadFolders():Promise<void>{const r=await PigeAPI.request<{items:Folder[]}>(base()+'/folders');s.folders=r.items;if(!s.folders.some(x=>x.id===s.folder))s.folder=s.folders.find(x=>x.role==='inbox')?.id||s.folders[0]?.id||'';}
    async function loadMessages():Promise<void>{if(!s.folder){s.items=[];return;}const params=new URLSearchParams({folder:s.folder,limit:'25',q:s.activeQuery});if(s.cursor!==null)params.set('before_uid',String(s.cursor));const r=await PigeAPI.request<Page>(base()+'/messages?'+params);s.items=r.items;s.next=r.next_before_uid;}
    async function loadAccount():Promise<void>{s.account=await PigeAPI.request<Account>(base()+'/account');if(s.account.connected){await loadFolders();await loadMessages();}}
    async function refresh():Promise<void>{await run(async()=>{await loadAccount();s.notice='Caixa atualizada.';});}
    async function connect():Promise<void>{await run(async()=>{await PigeAPI.post(base()+'/connection',{password:s.password});s.password='';s.showConnection=false;await loadAccount();s.notice='E-mail conectado.';});s.password='';}
    async function disconnect():Promise<void>{await run(async()=>{await PigeAPI.request(base()+'/connection',{method:'DELETE'});s.disconnectConfirm=false;s.selected=null;s.items=[];s.folders=[];await loadAccount();s.notice='Conexão encerrada. Suas mensagens permanecem na caixa.';});}
    async function selectFolder(id:string):Promise<void>{await run(async()=>{s.folder=id;s.cursor=null;s.cursors=[];s.selected=null;s.items=[];s.q='';s.activeQuery='';s.showFolders=false;s.deleteConfirm=false;await loadMessages();});}
    async function search():Promise<void>{await run(async()=>{s.activeQuery=s.q.trim();s.cursor=null;s.cursors=[];s.selected=null;await loadMessages();});}
    async function nextPage():Promise<void>{if(s.next===null)return;await run(async()=>{const old=s.cursor;s.cursor=s.next;try{await loadMessages();s.cursors.push(old);s.selected=null;}catch(e){s.cursor=old;throw e;}});}
    async function previousPage():Promise<void>{if(!s.cursors.length)return;await run(async()=>{const old=s.cursor;s.cursor=s.cursors.at(-1)??null;try{await loadMessages();s.cursors.pop();s.selected=null;}catch(e){s.cursor=old;throw e;}});}
    async function open(message:Message):Promise<void>{await run(async()=>{s.selected=await PigeAPI.request<Message>(messagePath(message)+'?'+query(message));s.deleteConfirm=false;s.moveTo='';if(!message.seen){await PigeAPI.patch(messagePath(message)+'/flags',{folder:s.folder,uidvalidity:message.uidvalidity,seen:true});message.seen=true;s.selected.seen=true;const current=folder();if(current)current.unread=Math.max(0,current.unread-1);}await Vue.nextTick();document.getElementById('email-reading-title')?.focus({preventScroll:true});});}
    async function flag():Promise<void>{const m=s.selected;if(!m)return;await run(async()=>{await PigeAPI.patch(messagePath(m)+'/flags',{folder:s.folder,uidvalidity:m.uidvalidity,flagged:!m.flagged});m.flagged=!m.flagged;const row=s.items.find(x=>x.uid===m.uid);if(row)row.flagged=m.flagged;});}
    async function unread():Promise<void>{const m=s.selected;if(!m)return;await run(async()=>{await PigeAPI.patch(messagePath(m)+'/flags',{folder:s.folder,uidvalidity:m.uidvalidity,seen:false});s.selected=null;await loadFolders();await loadMessages();s.notice='Mensagem marcada como não lida.';});}
    async function move(destination:string):Promise<void>{const m=s.selected;if(!m||!destination||destination===s.folder)return;await run(async()=>{await PigeAPI.post(messagePath(m)+'/move',{folder:s.folder,uidvalidity:m.uidvalidity,destination});s.selected=null;s.deleteConfirm=false;await loadFolders();await loadMessages();s.notice='Mensagem movida.';});}
    function moveRole(role:string):void{const target=s.folders.find(x=>x.role===role);if(target)void move(target.id);else s.error='Esta pasta ainda não está disponível. Crie uma pasta ou atualize a caixa.';}
    async function remove():Promise<void>{const m=s.selected;if(!m||!s.deleteConfirm)return;await run(async()=>{await PigeAPI.request(messagePath(m)+'?'+query(m)+'&confirm=true',{method:'DELETE'});s.selected=null;s.deleteConfirm=false;await loadFolders();await loadMessages();s.notice='Mensagem excluída definitivamente.';});}
    async function newFolder():Promise<void>{await run(async()=>{await PigeAPI.post(base()+'/folders',{name:s.newFolder.trim()});s.newFolder='';s.showNewFolder=false;await loadFolders();s.notice='Pasta criada.';});}
    function manageFolder():void{if(folder()?.role!=='custom')return;s.folderRename=folder()?.name||'';s.folderDeleteConfirm=false;s.folderEdit=true;}
    async function renameFolder():Promise<void>{if(folder()?.role!=='custom')return;await run(async()=>{const renamed=await PigeAPI.patch<Folder>(base()+'/folders/'+encodeURIComponent(s.folder),{name:s.folderRename.trim()});s.folder=renamed.id;s.selected=null;s.items=[];s.folderEdit=false;await loadFolders();await loadMessages();s.notice='Pasta renomeada.';});}
    async function deleteFolder():Promise<void>{if(folder()?.role!=='custom'||!s.folderDeleteConfirm)return;await run(async()=>{await PigeAPI.request(base()+'/folders/'+encodeURIComponent(s.folder)+'?confirm=true',{method:'DELETE'});s.folderEdit=false;s.selected=null;s.cursor=null;s.cursors=[];await loadFolders();await loadMessages();s.notice='Pasta vazia excluída.';});}
    async function download(attachment:Attachment):Promise<void>{const m=s.selected;if(m)await run(()=>PigeAPI.download(messagePath(m)+'/attachments/'+encodeURIComponent(attachment.part)+'?'+query(m),attachment.filename||'anexo'));}
    function begin(mode:'new'|'reply'|'all'|'forward'='new'):void{if(s.busy)return;const m=s.selected;const form=empty();if(m&&mode!=='new'){form.subject=(/^(re|res|enc|fw|fwd):/i.test(m.subject)?'':mode==='forward'?'Enc: ':'Re: ')+m.subject;form.text='\n\n'+(mode==='forward'?'---------- Mensagem encaminhada ----------\n':'Em '+date(m.date,true)+', '+m.from+' escreveu:\n')+(mode==='forward'?'De: '+m.from+'\nPara: '+m.to+'\nData: '+date(m.date,true)+'\nAssunto: '+m.subject+'\n\n':'')+(m.text||'');if(mode!=='forward'){form.to=headerAddresses(m.from);form.in_reply_to=m.message_id||'';if(mode==='all'){const own=s.account?.address.toLowerCase();form.cc=Array.from(new Set(addresses(headerAddresses(m.to)+','+headerAddresses(m.cc)).filter(x=>x.toLowerCase()!==own&&!addresses(form.to).includes(x)))).join(', ');}}}s.compose=form;s.composeInitial=JSON.stringify(empty());s.showCopies=Boolean(form.cc);s.discard=false;s.composeError='';s.composeNotice='';s.sendId='';s.pendingPayload=null;s.sendResult=null;}
    async function copyAttachments(m:Message):Promise<Upload[]>{const result:Upload[]=[];let total=0;for(const a of m.attachments||[]){total+=a.size;if(total>(s.account?.limits?.attachment_bytes||5242880)||result.length>=10)throw new Error('Os anexos ultrapassam o limite para edição. Baixe-os e prepare uma nova mensagem.');const url=await PigeAPI.objectUrl(messagePath(m)+'/attachments/'+encodeURIComponent(a.part)+'?'+query(m));try{const bytes=new Uint8Array(await (await fetch(url)).arrayBuffer());result.push({filename:a.filename,content_type:a.content_type,content_base64:base64(bytes),size:bytes.length});}finally{URL.revokeObjectURL(url);}}return result;}
    async function editDraft():Promise<void>{const m=s.selected;if(!m)return;await run(async()=>{const form=empty();form.to=headerAddresses(m.to);form.cc=headerAddresses(m.cc);form.bcc=headerAddresses(m.bcc);form.subject=m.subject;form.text=m.text||'';form.in_reply_to=m.in_reply_to||'';form.draft={folder:s.folder,uid:m.uid,uidvalidity:m.uidvalidity};form.attachments=await copyAttachments(m);s.compose=form;s.composeInitial=JSON.stringify(form);s.showCopies=Boolean(form.cc||form.bcc);s.discard=false;s.composeError='';s.composeNotice='';s.sendId='';s.pendingPayload=null;s.sendResult=null;});}
    async function forward():Promise<void>{const m=s.selected;if(!m)return;await run(async()=>{const attachments=await copyAttachments(m);s.busy=false;begin('forward');s.busy=true;if(s.compose)s.compose.attachments=attachments;});}
    function closeCompose(force=false):void{if(s.busy)return;if(!force&&!s.sendResult&&dirty()){s.discard=true;return;}if(!force&&s.pendingPayload&&!['sent','failed'].includes(s.sendResult?.status||'')){s.discard=true;return;}s.compose=null;s.pendingPayload=null;s.sendId='';s.sendResult=null;s.discard=false;s.composeError='';}
    async function addFiles(event:Event):Promise<void>{const input=event.target as HTMLInputElement;const files=Array.from(input.files||[]);input.value='';if(!s.compose||s.pendingPayload||s.busy)return;s.composeError='';try{let total=s.compose.attachments.reduce((n,a)=>n+a.size,0);if(s.compose.attachments.length+files.length>10)throw new Error('Adicione no máximo 10 anexos.');for(const file of files){total+=file.size;if(total>(s.account?.limits?.attachment_bytes||5242880))throw new Error('Os anexos juntos podem ter no máximo 5 MB.');}s.busy=true;const additions:Upload[]=[];for(const file of files)additions.push({filename:file.name,content_type:file.type||'application/octet-stream',content_base64:base64(new Uint8Array(await file.arrayBuffer())),size:file.size});s.compose.attachments.push(...additions);}catch(error){s.composeError=error instanceof Error?error.message:'Não foi possível anexar o arquivo.';}finally{s.busy=false;}}
    function payload(send=false):Record<string,unknown>{const form=s.compose!;const to=addresses(form.to),cc=addresses(form.cc),bcc=addresses(form.bcc);const all=[...to,...cc,...bcc];if(send&&!all.length)throw new Error('Informe ao menos um destinatário.');if(all.length>(s.account?.limits?.recipients||50))throw new Error('Use no máximo 50 destinatários por mensagem.');if(all.some(x=>! /^[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+$/.test(x)))throw new Error('Confira os endereços dos destinatários. Separe cada endereço por vírgula.');return {to,cc,bcc,subject:form.subject,text:form.text,attachments:form.attachments.map(({size:_,...a})=>a),...(form.in_reply_to?{in_reply_to:form.in_reply_to}:{}),...(form.draft?{draft:form.draft}:{})};}
    async function saveDraft():Promise<void>{if(s.busy||!s.compose||s.pendingPayload)return;s.busy=true;s.composeError='';try{const result=await PigeAPI.post<Draft&{previous_removed:boolean}>(base()+'/drafts',payload());s.compose.draft={folder:result.folder,uid:result.uid,uidvalidity:result.uidvalidity};s.composeInitial=JSON.stringify(s.compose);s.composeNotice=result.previous_removed===false?'Rascunho salvo. A cópia anterior permanece na pasta.':'Rascunho salvo.';await loadFolders();}catch(error){s.composeError=error instanceof Error?error.message:'Não foi possível salvar o rascunho.';}finally{s.busy=false;}}
    async function send():Promise<void>{if(s.busy||!s.compose)return;s.composeError='';s.composeNotice='';try{if(!s.pendingPayload){s.sendId=crypto.randomUUID();s.pendingPayload={...payload(true),request_id:s.sendId};}s.busy=true;s.sendResult=await PigeAPI.post<SendResult>(base()+'/send',s.pendingPayload);if(s.sendResult.status==='sent'){s.notice=s.sendResult.sent_saved?'Mensagem enviada.':'Mensagem enviada; a cópia não pôde ser salva em Enviados.';try{await loadFolders();await loadMessages();}catch{/* O envio confirmado não depende da atualização da listagem. */}}}catch(error){if(s.pendingPayload){const status=Number((error as {status?:number}).status||0);const rejected=[400,401,403,404,409,413,422].includes(status);s.sendResult={status:rejected?'failed':'uncertain',message_id:'',sent_saved:false,refused:[],message:rejected&&error instanceof Error?error.message:'A confirmação do envio não chegou. Consulte a situação antes de preparar outra mensagem.'};}else s.composeError=error instanceof Error?error.message:'Confira os dados da mensagem.';}finally{s.busy=false;}}
    function editAfterFailure():void{if(s.sendResult?.status!=='failed')return;s.pendingPayload=null;s.sendId='';s.sendResult=null;}
    async function showSettings():Promise<void>{await run(async()=>{s.settings=await PigeAPI.request<typeof s.settings>(base()+'/settings');s.showSettings=true;});}
    async function saveSettings():Promise<void>{await run(async()=>{s.settings=await PigeAPI.request<typeof s.settings>(base()+'/settings',{method:'PUT',body:JSON.stringify(s.settings)});s.showSettings=false;s.notice='Configuração de conexão salva.';await loadAccount();});}
    function beforeUnload(event:BeforeUnloadEvent):void{if(dirty()&&s.sendResult?.status!=='sent'){event.preventDefault();event.returnValue='';}}
    Vue.onMounted(()=>{unsavedWork=()=>Boolean(s.compose&&(dirty()||s.pendingPayload)&&s.sendResult?.status!=='sent');window.addEventListener('beforeunload',beforeUnload);void run(loadAccount);});
    Vue.onUnmounted(()=>{unsavedWork=()=>false;window.removeEventListener('beforeunload',beforeUnload);s.password='';s.compose=null;s.pendingPayload=null;});
    return {s,props,folder,folderName,folderIcon,date,size,dirty,refresh,connect,disconnect,selectFolder,search,nextPage,previousPage,open,flag,unread,move,moveRole,remove,newFolder,manageFolder,renameFolder,deleteFolder,download,begin,editDraft,forward,closeCompose,addFiles,saveDraft,send,editAfterFailure,showSettings,saveSettings};
  }};
}
