namespace PigeExpansion {
  type Campaign=PigeOnline.Campaign;type Admission=PigeOnline.Admission;type Charge=PigeOnline.Charge;
  type Props={schoolId:string;page:string;permissions:string[]};
  type ConnectInstance={id:string;version:number;name:string;display_name:string;document:string;primary:boolean;enabled:boolean;status:string;connection_state:string;external_id:string;last_error:string;last_synced_at:string|null;remote_configured:boolean};
  type ConnectJob={id:string;version:number;kind:string;status:string;attempts:number;error_code:string;delivery_status:string;remote_id:string;created_at:string};
  const emptyCampaign=()=>({id:'',version:1,slug:'',title:'',instructions:'',privacy_notice:'',terms_version:'1',class_group_ids:[] as string[],opens_on:new Date().toISOString().slice(0,10),closes_on:'',active:false,require_verified_contact:true,require_documents:false,require_payment_before_enrollment:false});
  const connectConfig=():PigeOnline.ConnectConfig=>({base_url:'',instance:'',send_text_path:'',connection_state_path:'',api_key_header:'apikey',auth_scheme:'',number_field:'number',text_field:'text',message_id_path:'key.id',contract_confirmed:false});
  export const component={props:['schoolId','page','permissions'],render:PigeRenders.expansion,setup(props:Props){
    const s=Vue.reactive({busy:false,error:'',notice:'',q:'',status:'',page:1,total:0,tab:'queue',rows:[] as Admission[],selected:null as Admission|null,campaigns:[] as Campaign[],campaignForm:emptyCampaign(),editingCampaign:false,groups:[] as PigeAPI.Row[],counts:{} as Record<string,number>,reason:'',action:'review',identity:false,existingStudent:'',existingGuardian:'',matchQ:'',studentMatches:[] as PigeAPI.Student[],guardianMatches:[] as PigeAPI.Row[],message:'',internal:false,charges:[] as Charge[],bankSummary:[] as {status:string;count:number;amount:string}[],selectedCharge:null as Charge|null,bankEvents:[] as PigeOnline.BankEvent[],bankReason:'',chargeOpen:false,chargeForm:{admission_id:'',enrollment_id:'',amount:'',due_on:'',description:'',billing_type:'PIX',client_key:PigeOnline.newId(),installment_count:1,required_for_enrollment:false},enrollmentQ:'',enrollmentMatches:[] as PigeAPI.Row[],connections:[] as PigeOnline.Connection[],jobs:[] as PigeOnline.Job[],jobTotal:0,jobPage:1,jobStatus:'',provider:'asaas',connectionForm:{version:undefined as number|undefined,enabled:false,environment:'sandbox',api_key:'',webhook_token:'',config:connectConfig()},editingConnection:false,connect:{configured:false,base_url:'',api_key_configured:false,instance_prefix:'PG360'},connectInstances:[] as ConnectInstance[],connectJobs:[] as ConnectJob[],connectJobTotal:0,connectJobPage:1,connectJobStatus:'',connectLabel:'',connectPrimary:false,connectNumber:'',connectQr:{base64:'',code:'',pairingCode:''}}});
    const base=()=>'/schools/'+props.schoolId;
    const can=(p:string)=>props.permissions.includes(p);
    const str=(v:unknown)=>v==null?'':String(v);
    async function run(action:()=>Promise<void>):Promise<void>{if(s.busy)return;s.busy=true;s.error='';s.notice='';try{await action();}catch(e){s.error=e instanceof Error?e.message:String(e);}finally{s.busy=false;}}
    async function queue():Promise<void>{const result=await PigeAPI.request<PigeOnline.Page<Admission>>(base()+`/admissions?page=${s.page}&q=${encodeURIComponent(s.q)}&status=${s.status}`);s.rows=result.items;s.total=result.total;const summary=await PigeAPI.request<{counts:Record<string,number>}>(base()+'/admissions-summary');s.counts=summary.counts;}
    async function bankList():Promise<void>{const result=await PigeAPI.request<PigeOnline.Page<Charge>>(base()+`/bank-charges?page=${s.page}&q=${encodeURIComponent(s.q)}&status=${s.status}`);s.charges=result.items;s.total=result.total;s.bankSummary=(await PigeAPI.request<{items:typeof s.bankSummary}>(base()+'/bank-summary')).items;}
    async function jobs():Promise<void>{const result=await PigeAPI.request<PigeOnline.Page<PigeOnline.Job>>(base()+`/integration-jobs?page=\${s.jobPage}&status=\${s.jobStatus}`);s.jobs=result.items;s.jobTotal=result.total;}
    async function connectJobs():Promise<void>{const result=await PigeAPI.request<{items:ConnectJob[];total:number}>(base()+`/connect/jobs?page=\${s.connectJobPage}&status=\${s.connectJobStatus}`);s.connectJobs=result.items;s.connectJobTotal=result.total;}
    async function connectLoad():Promise<void>{const result=await PigeAPI.request<{config:typeof s.connect;items:ConnectInstance[]}>(base()+'/connect');s.connect=result.config;s.connectInstances=result.items;await connectJobs();}
    function clearConnectQr():void{s.connectQr={base64:'',code:'',pairingCode:''};}
    function applyConnectQr(value:unknown):void{const qr=(value as {qrcode?:{base64?:string;code?:string;pairingCode?:string}}|null)?.qrcode||{};s.connectQr={base64:qr.base64||'',code:qr.code||'',pairingCode:qr.pairingCode||''};}
    async function connectCreate():Promise<void>{await run(async()=>{const result=await PigeAPI.post<{qrcode?:unknown}>(base()+'/connect/instances',{label:s.connectLabel,primary:s.connectPrimary});applyConnectQr(result);s.connectLabel='';s.connectPrimary=false;await connectLoad();s.notice='Instância criada na Connect API. Use QR Code ou pairing code para conectar o WhatsApp.';});}
    async function connectSync(instance:ConnectInstance):Promise<void>{await run(async()=>{const result=await PigeAPI.post<{qrcode?:unknown}>(base()+'/connect/instances/'+instance.id+'/sync',{});applyConnectQr(result);await connectLoad();});}
    async function connectPair(instance:ConnectInstance):Promise<void>{await run(async()=>{const result=await PigeAPI.post<{qrcode?:unknown}>(base()+'/connect/instances/'+instance.id+'/connect',{number:s.connectNumber});applyConnectQr(result);s.connectNumber='';await connectLoad();s.notice='Solicitação de conexão enviada. Se o QR não aparecer, atualize o estado da instância.';});}
    async function connectLogout(instance:ConnectInstance):Promise<void>{await run(async()=>{await PigeAPI.post(base()+'/connect/instances/'+instance.id+'/logout',{});clearConnectQr();await connectLoad();s.notice='Instância deslogada. O cadastro remoto foi preservado.';});}
    async function connectDelete(instance:ConnectInstance):Promise<void>{if(!window.confirm('Descadastrar a instância '+instance.name+' também na Connect API?'))return;await run(async()=>{await PigeAPI.request(base()+'/connect/instances/'+instance.id,{method:'DELETE'});clearConnectQr();await connectLoad();s.notice='Instância descadastrada na Connect API e mantida no histórico local.';});}
    async function connectTest():Promise<void>{await run(async()=>{const result=await PigeAPI.post<{message:string}>(base()+'/connect/test',{});s.notice=result.message;});}
    async function connectRetry(job:ConnectJob):Promise<void>{await run(async()=>{await PigeAPI.post(base()+'/connect/jobs/'+job.id+'/retry',{reason:s.reason});await connectJobs();s.notice='Mensagem devolvida à fila própria da Connect API.';});}
    async function load():Promise<void>{if(props.page==='online'){s.campaigns=await PigeAPI.request<Campaign[]>(base()+'/admission-campaigns');s.groups=await PigeAPI.request<PigeAPI.Row[]>(base()+'/class-groups');await queue();}else if(props.page==='banking'){await bankList();}else if(props.page==='connect'){await connectLoad();}else{s.connections=await PigeAPI.request<PigeOnline.Connection[]>(base()+'/integrations');await jobs();}}
    async function search():Promise<void>{s.page=1;await run(()=>props.page==='online'?queue():bankList());}
    async function paginate(n:number):Promise<void>{s.page+=n;await run(()=>props.page==='online'?queue():bankList());}
    async function paginateJobs(n:number):Promise<void>{s.jobPage+=n;await run(jobs);}
    function newCampaign():void{s.campaignForm=emptyCampaign();s.editingCampaign=true;}
    function editCampaign(c:Campaign):void{const {id,version,slug,title,instructions,privacy_notice,terms_version,class_group_ids,opens_on,closes_on,active,require_verified_contact,require_documents,require_payment_before_enrollment}=c;s.campaignForm={id,version,slug,title,instructions,privacy_notice,terms_version,class_group_ids:[...class_group_ids],opens_on,closes_on,active,require_verified_contact,require_documents,require_payment_before_enrollment};s.editingCampaign=true;}
    async function saveCampaign():Promise<void>{await run(async()=>{const {id,version,...data}=s.campaignForm;if(id)await PigeAPI.patch(base()+'/admission-campaigns/'+id,{...data,version});else await PigeAPI.post(base()+'/admission-campaigns',data);s.editingCampaign=false;await load();s.notice='Processo salvo. Divulgue somente processos ativos com prazos e ofertas conferidos.';});}
    async function openAdmission(id:string):Promise<void>{s.selected=await PigeAPI.request<Admission>(base()+'/admissions/'+id);s.identity=false;s.studentMatches=[];s.guardianMatches=[];s.existingStudent='';s.existingGuardian='';s.charges=(await PigeAPI.request<PigeOnline.Page<Charge>>(base()+'/bank-charges?admission_id='+id)).items;}
    async function view(id:string):Promise<void>{await run(()=>openAdmission(id));}
    async function action():Promise<void>{await run(async()=>{const a=s.selected;if(!a)return;await PigeAPI.post(base()+'/admissions/'+a.id+'/actions',{version:a.version,action:s.action,reason:s.reason});await openAdmission(a.id);await queue();s.reason='';});}
    async function match():Promise<void>{await run(async()=>{const q=encodeURIComponent(s.matchQ);s.studentMatches=(await PigeAPI.request<PigeOnline.Page<PigeAPI.Student>>(base()+'/students?q='+q)).items;s.guardianMatches=(await PigeAPI.request<PigeOnline.Page<PigeAPI.Row>>(base()+'/persons?guardians_only=true&q='+q)).items;});}
    async function approve():Promise<void>{await run(async()=>{const a=s.selected;if(!a)return;await PigeAPI.post(base()+'/admissions/'+a.id+'/approve',{version:a.version,reason:s.reason,identity_confirmed:s.identity,existing_student_id:s.existingStudent||null,existing_guardian_id:s.existingGuardian||null});await openAdmission(a.id);await queue();s.reason='';s.notice='Inscrição aprovada; matrícula criada como rascunho. Confira documentação e cobrança antes de efetivar.';});}
    async function finalize():Promise<void>{await run(async()=>{const a=s.selected;if(!a)return;await PigeAPI.post(base()+'/admissions/'+a.id+'/finalize',{version:a.version,reason:s.reason});await openAdmission(a.id);await queue();s.reason='';s.notice='Matrícula efetivada. Comprovante disponível no portal do responsável.';});}
    async function reviewDoc(item:PigeOnline.Attachment,status:string):Promise<void>{await run(async()=>{const a=s.selected;if(!a)return;await PigeAPI.post(base()+`/admissions/${a.id}/attachments/${item.id}/review`,{version:item.version,status,note:s.reason});await openAdmission(a.id);});}
    async function message():Promise<void>{await run(async()=>{if(!s.selected)return;await PigeAPI.post(base()+'/admissions/'+s.selected.id+'/messages',{text:s.message,internal:s.internal});s.message='';await openAdmission(s.selected.id);});}
    async function whatsapp():Promise<void>{await run(async()=>{if(!s.selected)return;await PigeAPI.post(base()+'/connect/messages',{admission_id:s.selected.id,text:s.message,client_key:PigeOnline.newId()});s.message='';s.notice='Envio enfileirado na Connect API. Consulte o resultado em Integrações.';});}
    async function download(path:string,name:string):Promise<void>{await run(()=>PigeAPI.download(base()+path,name));}
    function newCharge(admissionId=''):void{s.chargeForm={admission_id:admissionId,enrollment_id:'',amount:'',due_on:new Date(Date.now()+7*86400000).toISOString().slice(0,10),description:admissionId?'Matrícula':'Mensalidade',billing_type:'PIX',client_key:PigeOnline.newId(),installment_count:1,required_for_enrollment:false};s.enrollmentMatches=[];s.chargeOpen=true;}
    async function findEnrollments():Promise<void>{await run(async()=>{s.enrollmentMatches=(await PigeAPI.request<PigeOnline.Page<PigeAPI.Row>>(base()+'/enrollments?q='+encodeURIComponent(s.enrollmentQ))).items;});}
    async function createCharge():Promise<void>{await run(async()=>{const f=s.chargeForm;await PigeAPI.post(base()+'/bank-charges',{...f,admission_id:f.admission_id||null,enrollment_id:f.enrollment_id||null,installment_count:Number(f.installment_count)});s.chargeOpen=false;if(props.page==='banking')await bankList();else if(s.selected)await openAdmission(s.selected.id);s.notice='Cobrança(s) enfileirada(s). Emissão e atualização serão processadas pelo worker.';});}
    async function inspectCharge(c:Charge):Promise<void>{await run(async()=>{s.selectedCharge=c;s.bankReason='';s.bankEvents=await PigeAPI.request<PigeOnline.BankEvent[]>(base()+'/bank-charges/'+c.id+'/events');});}
    async function chargeAction(action:string):Promise<void>{await run(async()=>{const c=s.selectedCharge;if(!c)return;await PigeAPI.post(base()+'/bank-charges/'+c.id+'/'+action,{reason:s.bankReason});s.selectedCharge=null;if(props.page==='banking')await bankList();else if(s.selected)await openAdmission(s.selected.id);s.notice=action==='authorize-reissue'?'Reemissão autorizada após conferência. Acompanhe a fila.':'Solicitação registrada. Aguarde o processamento e atualize a consulta.';});}
    function configure(provider:string):void{s.provider=provider;const c=s.connections.find(c=>c.provider===provider);s.connectionForm={version:c?.version,enabled:c?.enabled||false,environment:c?.environment||'sandbox',api_key:'',webhook_token:'',config:{...connectConfig(),...c?.config}};s.editingConnection=true;}
    async function saveConnection():Promise<void>{await run(async()=>{const f=s.connectionForm;await PigeAPI.post(base()+'/integrations/'+s.provider,{...f,config:s.provider==='asaas'?{}:f.config});f.api_key='';f.webhook_token='';s.editingConnection=false;await load();s.notice='Configuração salva. O teste HTTP não substitui a homologação de mensagens e cobranças.';});}
    async function testConnection(provider:string):Promise<void>{await run(async()=>{const r=await PigeAPI.post<{ok:boolean;code:string;message:string}>(base()+'/integrations/'+provider+'/test',{});await load();if(!r.ok)throw new Error(r.message+' Código: '+r.code);s.notice=r.message;});}
    async function retry(job:PigeOnline.Job):Promise<void>{await run(async()=>{await PigeAPI.post(base()+'/integration-jobs/'+job.id+'/retry',{reason:s.reason});await jobs();});}
    async function copy(value:string):Promise<void>{await run(async()=>{await navigator.clipboard.writeText(value);s.notice='Copiado.';});}
    const connectionFor=(provider:string)=>s.connections.find(c=>c.provider===provider);
    Vue.onMounted(()=>{void run(load);});
    return {s,props,can,str,run,load,search,paginate,paginateJobs,newCampaign,editCampaign,saveCampaign,view,action,match,approve,finalize,reviewDoc,message,whatsapp,download,newCharge,findEnrollments,createCharge,inspectCharge,chargeAction,configure,saveConnection,testConnection,retry,copy,connectionFor,jobs,connectLoad,connectJobs,connectCreate,connectSync,connectPair,connectLogout,connectDelete,connectTest,connectRetry,clearConnectQr,label:PigeOnline.label,date:PigeOnline.date,money:PigeOnline.money,publicURL:PigeOnline.publicURL,safeLink:PigeOnline.safeLink,origin:location.origin,statuses:PigeOnline.statuses};
  }};
}
