namespace PigeExpansion {
  type Campaign=PigeOnline.Campaign;type Admission=PigeOnline.Admission;type Charge=PigeOnline.Charge&{collection_mode:'manual'|'provider';manual_paid_on?:string;manual_paid_amount?:string;manual_payment_method?:string;manual_reference?:string;last_synced_at?:string;issuance?:{status:string;error_code:string;attempts:number}|null};
  type BankingStatus={configured:boolean;enabled:boolean;environment:string;last_test_ok:boolean|null;last_test_at:string|null;webhook_registered:boolean;last_webhook_at:string|null;pending_jobs:number;failed_jobs:number;queue_delayed:boolean};
  type Props={schoolId:string;page:string;permissions:string[]};
  type ConnectInstance={id:string;version:number;name:string;display_name:string;document:string;primary:boolean;enabled:boolean;status:string;connection_state:string;external_id:string;phone:string;source:'pige360'|'adopted';last_error:string;last_synced_at:string|null;remote_configured:boolean;preferred_for_school:boolean;managed_by_pige360:boolean};
  type RemoteConnectInstance={name:string;state:string;integration:string;number:string;external_id:string;registered:boolean;local_id:string;source:string};
  type ConnectUnitPreference={id:string;name:string;preferred_instance_id:string};
  type ConnectJob={id:string;version:number;kind:string;status:string;attempts:number;error_code:string;delivery_status:string;remote_id:string;created_at:string};
  type ConnectQrResult={qrcode?:{base64?:string;code?:string;pairingCode?:string};base64?:string;code?:string;pairingCode?:string;instance?:ConnectInstance;connected?:boolean;pending?:boolean};
  type ConnectQrDisplay={instanceId:string;base64:string;code:string;pairingCode:string;pending:boolean;connected:boolean;kind:'qr'|'pairing'|'create'|''};
  type ContractTemplate=PigeAPI.Row&{name:string;kind:string;active:boolean;require_signature:boolean;academic_year_id:string|null};
  type ContractPreview={header:string;content:string;footer:string;variables:Record<string,string>;missing_fields:string[];template_version:number};
  const defaultGuardianInstructions="Leia atentamente antes de iniciar a inscrição.\n\n1. Preencha os dados do aluno e do responsável exatamente como constam nos documentos oficiais.\n2. Informe e-mail e telefone atualizados, pois a instituição poderá utilizá-los para comunicações sobre a inscrição e a matrícula.\n3. Envie somente os documentos solicitados. Ao fotografar, enquadre o documento inteiro, com boa iluminação, sem reflexos e com os dados legíveis.\n4. Quando o sistema sugerir dados a partir da leitura de um documento, confira as informações antes de aplicá-las ao cadastro.\n5. Revise todos os dados antes de enviar a inscrição. Informações incompletas ou divergentes poderão exigir correção ou nova documentação.\n6. A inscrição online não garante vaga nem matrícula. A efetivação depende da análise da instituição, da disponibilidade de vaga e do cumprimento das etapas definidas para este processo.\n7. Acompanhe o andamento pelo Portal dos responsáveis e observe as mensagens, solicitações de ajuste, prazos e documentos pendentes.\n8. Em caso de dúvida ou dificuldade, entre em contato diretamente com a instituição pelos canais oficiais.";
  const defaultPrivacyNotice="A instituição é responsável pelo tratamento dos dados pessoais informados neste processo de inscrição e matrícula.\n\nOs dados do aluno e de seus responsáveis serão utilizados para receber e analisar a inscrição, conferir documentos, manter contato com a família, organizar o atendimento escolar, preparar e efetivar a matrícula quando aprovada, cumprir obrigações legais e regulatórias e proteger a segurança do processo.\n\nPoderão ser tratados dados de identificação, contato, endereço, informações acadêmicas e documentos necessários à inscrição. Dados pessoais sensíveis somente deverão ser solicitados e utilizados quando forem necessários ao atendimento educacional, à segurança, à acessibilidade, ao cumprimento de obrigação legal ou à proteção dos direitos do aluno, sempre considerando o seu melhor interesse.\n\nA instituição poderá utilizar prestadores indispensáveis à operação do serviço, como hospedagem, armazenamento, comunicação, meios de pagamento e suporte técnico, observando medidas de segurança e confidencialidade. Dados também poderão ser fornecidos a autoridades públicas quando houver obrigação legal ou determinação válida. Os dados não serão comercializados.\n\nAs informações serão mantidas pelo período necessário à análise da inscrição, à execução da relação escolar, ao cumprimento de obrigações legais e à preservação de direitos. Registros que não precisem mais ser mantidos deverão seguir a política de retenção da instituição.\n\nO responsável poderá solicitar à instituição informações sobre o tratamento, correção de dados inexatos e o exercício dos demais direitos aplicáveis previstos na legislação de proteção de dados, pelos canais oficiais de atendimento da escola.\n\nA instituição adota medidas técnicas e administrativas para proteger os dados contra acessos não autorizados, perda, alteração ou divulgação indevida. O envio de dados pela internet, entretanto, exige também que o responsável proteja suas credenciais de acesso e utilize dispositivos confiáveis.\n\nAutorizações opcionais, como o recebimento de comunicações por WhatsApp, devem ser apresentadas separadamente e podem ser alteradas conforme as opções disponibilizadas pela instituição.\n\nAo prosseguir, o responsável declara que leu este aviso e que as informações fornecidas são verdadeiras, sem que essa ciência substitua bases legais específicas exigidas para cada atividade de tratamento.";
  const emptyCampaign=()=>({id:'',version:1,slug:'',title:'',instructions:defaultGuardianInstructions,privacy_notice:defaultPrivacyNotice,terms_version:'1',class_group_ids:[] as string[],opens_on:new Date().toISOString().slice(0,10),closes_on:'',active:false,require_verified_contact:true,require_documents:false,require_payment_before_enrollment:false,contract_template_id:''});
  const connectConfig=():PigeOnline.ConnectConfig=>({base_url:'',instance:'',send_text_path:'',connection_state_path:'',api_key_header:'apikey',auth_scheme:'',number_field:'number',text_field:'text',message_id_path:'key.id',contract_confirmed:false});
  export const component={props:['schoolId','page','permissions'],render:PigeRenders.expansion,setup(props:Props){
    const s=Vue.reactive({readiness:null as null|{ready:boolean;server_date:string;issues:{code:string;message:string}[];campaigns:{id:string;title:string;ready:boolean;reasons:string[]}[]},busy:false,error:'',notice:'',q:'',status:'',page:1,total:0,tab:'queue',rows:[] as Admission[],selected:null as Admission|null,campaigns:[] as Campaign[],campaignForm:emptyCampaign(),editingCampaign:false,groups:[] as PigeAPI.Row[],campaignYears:[] as PigeAPI.Row[],campaignUnits:[] as PigeAPI.Row[],contractTemplates:[] as ContractTemplate[],contractFields:[] as {key:string;label:string;source:string}[],contractPreview:null as ContractPreview|null,contractValues:{} as Record<string,string>,contractPreviewStale:false,counts:{} as Record<string,number>,reason:'',action:'review',identity:false,existingStudent:'',existingGuardian:'',matchQ:'',studentMatches:[] as PigeAPI.Student[],guardianMatches:[] as PigeAPI.Row[],message:'',internal:false,charges:[] as Charge[],bankSummary:[] as {status:string;count:number;amount:string}[],bankDueFrom:'',bankDueTo:'',bankingStatus:null as BankingStatus|null,webhookEmail:'',showBankOperations:false,selectedCharge:null as Charge|null,bankEvents:[] as (PigeOnline.BankEvent&{details?:{amount?:string;paid_on?:string;reference?:string}})[],receiptForm:{amount:'',paid_on:'',payment_method:'cash',reference:'',client_key:PigeOnline.newId()},bankReason:'',chargeOpen:false,chargeInitial:'',discardCharge:false,chargeForm:{admission_id:'',enrollment_id:'',amount:'',due_on:'',description:'',collection_mode:'manual',billing_type:'MANUAL',client_key:PigeOnline.newId(),installment_count:1,required_for_enrollment:false},enrollmentQ:'',enrollmentMatches:[] as PigeAPI.Row[],connections:[] as PigeOnline.Connection[],jobs:[] as PigeOnline.Job[],jobTotal:0,jobPage:1,jobStatus:'',provider:'asaas',connectionForm:{version:undefined as number|undefined,enabled:false,environment:'sandbox',api_key:'',webhook_token:'',config:connectConfig()},editingConnection:false,connect:{configured:false,base_url:'',api_key_configured:false,instance_prefix:'PG360',host_policy:'base_url',effective_host:''},connectInstances:[] as ConnectInstance[],connectRemote:[] as RemoteConnectInstance[],connectInventoryLoaded:false,connectAdoptName:'',connectLegacyReview:false,connectLegacyConfirm:false,connectLegacyReason:'',connectUnits:[] as ConnectUnitPreference[],connectJobs:[] as ConnectJob[],connectJobTotal:0,connectJobPage:1,connectJobStatus:'',connectLabel:'',connectPrimary:false,connectCreatePhone:'',connectPhoneDrafts:{} as Record<string,string>,connectOperation:{instanceId:'',kind:''},connectQr:{instanceId:'',base64:'',code:'',pairingCode:'',pending:false,connected:false,kind:''} as ConnectQrDisplay});
    const base=()=>'/schools/'+props.schoolId;
    const can=(p:string)=>props.permissions.includes(p);
    const str=(v:unknown)=>v==null?'':String(v);
    async function run(action:()=>Promise<void>):Promise<void>{if(s.busy)return;s.busy=true;s.error='';s.notice='';try{await action();}catch(e){s.error=e instanceof Error?e.message:String(e);}finally{s.busy=false;}}
    function campaignYearId():string{const years=new Set(s.groups.filter(group=>s.campaignForm.class_group_ids.includes(group.id)).map(group=>str(group.academic_year_id)));return years.size===1?[...years][0]:'';}
    function eligibleContractTemplates():ContractTemplate[]{const year=campaignYearId();return s.contractTemplates.filter(template=>template.active&&template.require_signature&&(!year||!template.academic_year_id||template.academic_year_id===year));}
    function templateName(id:unknown):string{return s.contractTemplates.find(template=>template.id===id)?.name||'Nenhum contrato obrigatório';}
    function selectedContractVersion():number{return Number(s.selected?.contract_template_version||s.selected?.contract?.template_version||0);}
    function contractStatus(status:unknown):string{return ({awaiting_school:'Aguardando emissão pela escola',company_signed:'Assinado pela escola · aguardando responsável',pending_validation:'Assinatura do responsável em revisão',verified:'Assinatura conferida',rejected:'Devolvido para correção',unsigned:'Sem assinatura'} as Record<string,string>)[str(status)]||str(status)||'—';}
    function contractPreviewKeys():string[]{const preview=s.contractPreview;return preview?Array.from(new Set([...Object.keys(preview.variables||{}),...(preview.missing_fields||[])])):[];}
    function contractFieldLabel(key:string):string{return s.contractFields.find(field=>field.key===key)?.label||key;}
    function contractValue(key:string):string{return Object.prototype.hasOwnProperty.call(s.contractValues,key)?s.contractValues[key]:str(s.contractPreview?.variables?.[key]);}
    function contractAutomatic(key:string):boolean{return !Object.prototype.hasOwnProperty.call(s.contractValues,key)&&Boolean(s.contractPreview?.variables?.[key]);}
    function setContractValue(key:string,event:Event):void{s.contractValues[key]=(event.target as HTMLInputElement).value;s.contractPreviewStale=true;}
    async function previewFrozenContract():Promise<void>{await run(async()=>{const admission=s.selected,templateId=admission?.contract?.template_id||admission?.contract_template_id,version=selectedContractVersion();
      if(!admission?.enrollment_id||!templateId||!version)throw new Error('Contrato congelado ou matrícula da inscrição não encontrados.');
      s.contractPreview=await PigeAPI.post<ContractPreview>(base()+'/document-templates/'+templateId+'/preview',{enrollment_id:admission.enrollment_id,template_version:version,values:s.contractValues});s.contractPreviewStale=false;
    });}
    async function previewFrozenPdf():Promise<void>{await run(async()=>{const admission=s.selected,templateId=admission?.contract?.template_id||admission?.contract_template_id,version=selectedContractVersion();
      if(!admission?.enrollment_id||!templateId||!version)throw new Error('Contrato congelado ou matrícula não encontrados.');
      await PigeAPI.downloadPost(base()+'/document-templates/'+templateId+'/preview.pdf',{enrollment_id:admission.enrollment_id,template_version:version,values:s.contractValues},'previa-contrato-'+admission.number+'.pdf');
    });}
    async function issueFrozenContract():Promise<void>{await run(async()=>{const admission=s.selected,templateId=admission?.contract?.template_id||admission?.contract_template_id,version=selectedContractVersion();
      if(!admission?.enrollment_id||!templateId||!version||!s.contractPreview||s.contractPreviewStale||s.contractPreview.missing_fields.length)throw new Error('Revise a prévia e preencha todos os campos antes de emitir.');
      await PigeAPI.post(base()+'/document-templates/'+templateId+'/issue',{enrollment_id:admission.enrollment_id,template_version:version,values:s.contractValues});
      await openAdmission(admission.id);await queue();s.notice='Contrato emitido da revisão aprovada e assinado pela escola. O responsável pode baixar essa via para assinar; a matrícula aguarda conferência da assinatura externa.';
    });}
    async function downloadSignedContract():Promise<void>{await run(async()=>{const documentId=s.selected?.contract?.issued_document_id;if(!documentId)throw new Error('Contrato ainda não emitido.');
      const details=await PigeAPI.request<{file_id:string}>(base()+'/issued-documents/'+documentId+'/signatures');
      await PigeAPI.download(base()+'/files/'+details.file_id+'/download','contrato-assinado-pela-escola.pdf');
    });}
    async function queue():Promise<void>{const result=await PigeAPI.request<PigeOnline.Page<Admission>>(base()+`/admissions?page=${s.page}&q=${encodeURIComponent(s.q)}&status=${s.status}`);s.rows=result.items;s.total=result.total;const summary=await PigeAPI.request<{counts:Record<string,number>}>(base()+'/admissions-summary');s.counts=summary.counts;}
    function bankFilters():string{return new URLSearchParams({q:s.q,status:s.status,...(s.bankDueFrom?{due_from:s.bankDueFrom}:{}),...(s.bankDueTo?{due_to:s.bankDueTo}:{})}).toString();}
    async function bankHealth():Promise<void>{s.bankingStatus=await PigeAPI.request<BankingStatus>(base()+'/banking-status');}
    async function bankList():Promise<void>{
      const [result,summary]=await Promise.all([PigeAPI.request<PigeOnline.Page<Charge>>(base()+`/bank-charges?page=${s.page}&${bankFilters()}`),PigeAPI.request<{items:typeof s.bankSummary}>(base()+'/bank-summary?'+bankFilters())]);
      s.charges=result.items;s.total=result.total;s.bankSummary=summary.items;
    }
    function bankCards():{title:string;amount:string;count:number}[]{return [
      {title:'A receber',states:['queued','pending','confirmed']},{title:'Recebido',states:['received','received_external']},
      {title:'Em atraso',states:['overdue']},{title:'Exigem atenção',states:['failed','uncertain','disputed','awaiting_review']},
    ].map(card=>{const items=s.bankSummary.filter(item=>card.states.includes(item.status));return {title:card.title,amount:(items.reduce((total,item)=>total+Math.round(Number(item.amount)*100),0)/100).toFixed(2),count:items.reduce((total,item)=>total+item.count,0)};});}
    async function bankPeriod(months:number):Promise<void>{const today=new Date(),year=today.getFullYear(),month=today.getMonth();const iso=(value:Date)=>[value.getFullYear(),String(value.getMonth()+1).padStart(2,'0'),String(value.getDate()).padStart(2,'0')].join('-');s.bankDueFrom=months?iso(new Date(year,month-months+1,1)):'';s.bankDueTo=months?iso(new Date(year,month+1,0)):'';s.page=1;await run(bankList);}
    async function reconcileBank():Promise<void>{await run(async()=>{const result=await PigeAPI.post<{count:number;message:string}>(base()+'/bank-charges/reconcile?'+bankFilters(),{reason:'Conciliação das cobranças selecionadas no painel financeiro.'});await bankHealth();s.notice=result.count?result.message:'Não há cobranças emitidas pendentes de conciliação neste filtro.';});}
    function bankError(code:string):string{return ({PROVIDER_HTTP_401:'Chave da API inválida ou expirada.',PROVIDER_HTTP_403:'A conta não autorizou esta operação.',PROVIDER_HTTP_400:'O banco recusou os dados. Confira CPF, valor e vencimento.',PROVIDER_HTTP_429:'O banco limitou as consultas. A próxima tentativa será programada.',PROVIDER_TIMEOUT:'O banco demorou a responder. Confira a conciliação antes de reenviar.',PROVIDER_NETWORK_ERROR:'Não foi possível comunicar com o banco.',API_KEY_MISSING:'Cadastre a chave da conta bancária.',PAYMENT_POST_REQUIRES_RECONCILIATION:'Confira a emissão no banco antes de tentar novamente.',CUSTOMER_POST_REQUIRES_RECONCILIATION:'Confira o cadastro do pagador no banco antes de tentar novamente.',REMOTE_PAYMENT_NOT_FOUND:'A cobrança ainda não foi localizada no banco.',BANK_VALUE_MISMATCH:'O valor no banco diverge do lançamento. Confira a cobrança.',INTEGRATION_DISABLED:'A integração bancária está desabilitada.',DUPLICATE_BANK_WEBHOOK:'Há mais de um retorno com o mesmo endereço. Confira a configuração na conta.'} as Record<string,string>)[code]||'A operação precisa ser conferida pela administração.';}
    function bankOperation(kind:string):string{return ({bank_issue:'Emissão de cobrança',bank_sync:'Conciliação',bank_cancel:'Cancelamento',smtp_email:'Envio de e-mail',connect_text:'Mensagem WhatsApp'} as Record<string,string>)[kind]||'Operação da integração';}
    async function activateBankWebhook():Promise<void>{await run(async()=>{const result=await PigeAPI.post<{ok:boolean;code?:string;message:string}>(base()+'/integrations/asaas/webhook',{email:s.webhookEmail});if(!result.ok)throw new Error(result.message+(result.code?' '+bankError(result.code):''));await load();s.notice=result.message;});}
    async function jobs():Promise<void>{const result=await PigeAPI.request<PigeOnline.Page<PigeOnline.Job>>(base()+`/integration-jobs?page=${s.jobPage}&status=${s.jobStatus}`);s.jobs=result.items;s.jobTotal=result.total;}
    async function connectJobs():Promise<void>{const result=await PigeAPI.request<{items:ConnectJob[];total:number}>(base()+`/connect/jobs?page=${s.connectJobPage}&status=${s.connectJobStatus}`);s.connectJobs=result.items;s.connectJobTotal=result.total;}
    async function connectLoad():Promise<void>{const result=await PigeAPI.request<{config:typeof s.connect;items:ConnectInstance[];units:ConnectUnitPreference[];legacy_binding_requires_review?:boolean}>(base()+'/connect');s.connect=result.config;s.connectInstances=result.items;s.connectUnits=result.units||[];s.connectLegacyReview=Boolean(result.legacy_binding_requires_review);for(const i of result.items){s.connectPhoneDrafts[i.id]=i.phone||s.connectPhoneDrafts[i.id]||'';}await connectJobs();}
    async function refreshConnectInventory():Promise<void>{const result=await PigeAPI.request<{items:RemoteConnectInstance[]}>(base()+'/connect/remote-instances');s.connectRemote=result.items;s.connectInventoryLoaded=true;}
    async function connectInventory():Promise<void>{await run(async()=>{await refreshConnectInventory();s.notice='Inventário de instâncias do WhatsApp atualizado.';});}
    async function connectAdopt(remote:{name:string}):Promise<void>{await run(async()=>{const result=await PigeAPI.post<{instance?:ConnectInstance}>(base()+'/connect/instances/adopt',{instance_name:remote.name.trim(),primary:true});await refreshConnectAfterOperation(result.instance);try{await refreshConnectInventory();}catch(e){s.error='Instância vinculada, mas o inventário não pôde ser atualizado: '+(e instanceof Error?e.message:String(e));}s.connectAdoptName='';s.notice='Instância vinculada como preferencial desta instituição.';});}
    async function connectAdoptNamed():Promise<void>{if(!s.connectAdoptName.trim())return;await connectAdopt({name:s.connectAdoptName});}
    async function connectReleaseLegacy():Promise<void>{await run(async()=>{if(!s.connectLegacyConfirm||s.connectLegacyReason.trim().length<5)throw new Error('Informe o motivo para remover os vínculos anteriores.');await PigeAPI.post(base()+'/connect/legacy-bindings/release',{reason:s.connectLegacyReason.trim()});s.connectLegacyConfirm=false;s.connectLegacyReason='';await connectLoad();s.notice='Vínculos anteriores desta instituição removidos. A instância e os vínculos de outras instituições foram preservados.';});}
    async function connectPrefer(instance:ConnectInstance):Promise<void>{await run(async()=>{await PigeAPI.post(base()+'/connect/instances/'+instance.id+'/prefer',{});await connectLoad();s.notice='Instância definida como preferencial desta escola.';});}
    async function connectPreferUnit(unit:ConnectUnitPreference,instanceId:string):Promise<void>{await run(async()=>{await PigeAPI.post(base()+'/connect/unit-preference',{unit_id:unit.id,instance_id:instanceId});await connectLoad();s.notice=instanceId?'Preferência da unidade atualizada.':'A unidade voltou a usar a preferência da escola.';});}
    async function connectRestart(instance:ConnectInstance):Promise<void>{await run(async()=>{await PigeAPI.post(base()+'/connect/instances/'+instance.id+'/restart',{});await connectLoad();s.notice='Reinício solicitado para a instância administrada pelo PIGE360.';});}
    function clearConnectQr(instanceId?:string):void{if(!instanceId||s.connectQr.instanceId===instanceId)s.connectQr={instanceId:'',base64:'',code:'',pairingCode:'',pending:false,connected:false,kind:''};}
    function applyConnectQr(value:ConnectQrResult,instanceId:string,kind:ConnectQrDisplay['kind']):void{
      const qr=value.qrcode&&typeof value.qrcode==='object'?value.qrcode:value;
      const base64=typeof qr.base64==='string'?qr.base64:'';
      s.connectQr={instanceId,base64:/^data:image\/(png|jpe?g|webp|gif);base64,/i.test(base64)?base64:base64.startsWith('data:')?'':base64?'data:image/png;base64,'+base64:'',code:typeof qr.code==='string'?qr.code:'',pairingCode:typeof qr.pairingCode==='string'?qr.pairingCode:'',pending:false,connected:Boolean(value.connected),kind};
      s.connectQr.pending=!s.connectQr.connected&&(kind==='pairing'?!s.connectQr.pairingCode:kind==='qr'?!s.connectQr.base64:!s.connectQr.base64&&!s.connectQr.code&&!s.connectQr.pairingCode);
    }
    async function refreshConnectAfterOperation(instance?:ConnectInstance):Promise<void>{
      if(instance){const index=s.connectInstances.findIndex(item=>item.id===instance.id);if(index<0)s.connectInstances.push(instance);else s.connectInstances[index]=instance;s.connectPhoneDrafts[instance.id]=instance.phone||s.connectPhoneDrafts[instance.id]||'';}
      try{await connectLoad();}catch(e){s.error='A operação foi concluída, mas não foi possível atualizar a lista: '+(e instanceof Error?e.message:String(e));}
    }
    async function connectCreate():Promise<void>{await run(async()=>{s.connectOperation={instanceId:'new',kind:'create'};try{
      const result=await PigeAPI.post<ConnectQrResult>(base()+'/connect/instances',{label:s.connectLabel,phone:s.connectCreatePhone,primary:s.connectPrimary});
      if(!result.instance?.id)throw new Error('A instância foi criada, mas a resposta não trouxe seu identificador. Atualize a lista antes de tentar novamente.');
      applyConnectQr(result,result.instance.id,'create');s.connectLabel='';s.connectCreatePhone='';s.connectPrimary=false;
      await refreshConnectAfterOperation(result.instance);
      s.notice=s.connectQr.connected?'Instância criada e conectada ao WhatsApp.':s.connectQr.pending?'Instância criada. Gere o QR Code ou obtenha o código de pareamento para conectar o WhatsApp.':'Instância criada. Use o QR Code ou o código de pareamento exibido abaixo.';
    }finally{s.connectOperation={instanceId:'',kind:''};}});}
    async function connectSync(instance:ConnectInstance):Promise<void>{await run(async()=>{const result=await PigeAPI.post<ConnectQrResult>(base()+'/connect/instances/'+instance.id+'/sync',{});if(result.qrcode&&(result.qrcode.base64||result.qrcode.code||result.qrcode.pairingCode))applyConnectQr(result,instance.id,'qr');if(result.instance?.connection_state==='open')clearConnectQr(instance.id);await refreshConnectAfterOperation(result.instance);s.notice='Estado da instância consultado.';});}
    async function connectQr(instance:ConnectInstance):Promise<void>{await run(async()=>{s.connectOperation={instanceId:instance.id,kind:'qr'};clearConnectQr(instance.id);try{
      const result=await PigeAPI.post<ConnectQrResult>(base()+'/connect/instances/'+instance.id+'/qr',{});
      applyConnectQr(result,instance.id,'qr');await refreshConnectAfterOperation(result.instance);
      s.notice=s.connectQr.connected?'WhatsApp já conectado nesta instância.':s.connectQr.pending?(s.connectQr.code?'O provedor devolveu somente o texto do QR, sem imagem para escanear. Aguarde e tente novamente.':'Ainda não há QR Code disponível. Aguarde alguns instantes e tente novamente.'):'QR Code pronto para esta instância.';
    }finally{s.connectOperation={instanceId:'',kind:''};}});}
    async function connectPairingCode(instance:ConnectInstance):Promise<void>{await run(async()=>{s.connectOperation={instanceId:instance.id,kind:'pairing'};clearConnectQr(instance.id);try{
      const result=await PigeAPI.post<ConnectQrResult>(base()+'/connect/instances/'+instance.id+'/pairing-code',{});
      applyConnectQr(result,instance.id,'pairing');await refreshConnectAfterOperation(result.instance);
      s.notice=s.connectQr.connected?'WhatsApp já conectado nesta instância.':s.connectQr.pending?'Ainda não há código de pareamento disponível. Aguarde alguns instantes e tente novamente.':'Código de pareamento pronto para o telefone cadastrado.';
    }finally{s.connectOperation={instanceId:'',kind:''};}});}
    async function connectSavePhone(instance:ConnectInstance):Promise<void>{await run(async()=>{await PigeAPI.post(base()+'/connect/instances/'+instance.id+'/phone',{number:s.connectPhoneDrafts[instance.id]||''});await connectLoad();s.notice='Telefone da instância atualizado.';});}
    async function connectLogout(instance:ConnectInstance):Promise<void>{await run(async()=>{await PigeAPI.post(base()+'/connect/instances/'+instance.id+'/logout',{});clearConnectQr(instance.id);await connectLoad();s.notice='Instância deslogada. O cadastro remoto foi preservado.';});}
    async function connectDelete(instance:ConnectInstance):Promise<void>{const remote=instance.managed_by_pige360;const prompt=remote?'Excluir a instância '+instance.name+' também no provedor de WhatsApp?':'Desvincular '+instance.name+' desta instalação sem excluir a instância remota?';if(!window.confirm(prompt))return;await run(async()=>{const result=await PigeAPI.request<{remote_deleted?:boolean}>(base()+'/connect/instances/'+instance.id,{method:'DELETE'});clearConnectQr(instance.id);await connectLoad();s.notice=result.remote_deleted?'Instância criada pelo PIGE360 excluída do provedor de WhatsApp.':'Vínculo local removido; a instância preexistente foi preservada no provedor de WhatsApp.';});}
    async function connectTest():Promise<void>{await run(async()=>{const result=await PigeAPI.post<{message:string}>(base()+'/connect/test',{});s.notice=result.message;});}
    async function connectRetry(job:ConnectJob):Promise<void>{await run(async()=>{await PigeAPI.post(base()+'/connect/jobs/'+job.id+'/retry',{reason:s.reason});await connectJobs();s.notice='Mensagem devolvida à fila do WhatsApp.';});}
    async function load():Promise<void>{if(props.page==='online'){const [readiness,campaigns,groups,templates,fields,years,units]=await Promise.all([
      PigeAPI.request<typeof s.readiness>(base()+'/admission-readiness'),PigeAPI.request<Campaign[]>(base()+'/admission-campaigns'),
      can('admissions.manage')?PigeAPI.request<PigeAPI.Row[]>(base()+'/class-groups'):Promise.resolve([]),
      can('documents.read')?PigeAPI.request<{items:ContractTemplate[]}>(base()+'/document-templates'):Promise.resolve({items:[]}),
      can('documents.read')?PigeAPI.request<{fields:typeof s.contractFields}>(base()+'/document-templates/fields'):Promise.resolve({fields:[]}),
      can('admissions.manage')?PigeAPI.request<PigeAPI.Row[]>(base()+'/academic-years'):Promise.resolve([]),
      can('admissions.manage')?PigeAPI.request<PigeAPI.Row[]>(base()+'/units'):Promise.resolve([])]);
      s.readiness=readiness;s.campaigns=campaigns;s.groups=groups;s.contractTemplates=templates.items;s.contractFields=fields.fields;s.campaignYears=years;s.campaignUnits=units;await queue();
    }else if(props.page==='banking'){await Promise.all([bankList(),bankHealth()]);}else if(props.page==='connect'){await connectLoad();}else{s.connections=await PigeAPI.request<PigeOnline.Connection[]>(base()+'/integrations');await Promise.all([jobs(),bankHealth()]);}}
    async function search():Promise<void>{s.page=1;await run(()=>props.page==='online'?queue():bankList());}
    async function paginate(n:number):Promise<void>{s.page+=n;await run(()=>props.page==='online'?queue():bankList());}
    async function paginateJobs(n:number):Promise<void>{s.jobPage+=n;await run(jobs);}
    function campaignSlug():void{if(!s.campaignForm.id&&!s.campaignForm.slug)s.campaignForm.slug=s.campaignForm.title.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,80);}
    function campaignGroupLabel(group:PigeAPI.Row):string{const year=s.campaignYears.find(item=>item.id===group.academic_year_id);const unit=s.campaignUnits.find(item=>item.id===group.unit_id);return [group.name,year?.name,unit?.name].filter(Boolean).join(' · ');}
    function campaignGroups():PigeAPI.Row[]{return s.groups.filter(group=>s.campaignForm.class_group_ids.includes(group.id)||(group.active&&s.campaignYears.some(year=>year.id===group.academic_year_id&&year.status==='active')));}
    function admissionActions():{value:string;label:string}[]{
      const status=s.selected?.status||'';
      return [{value:'review',label:'Iniciar análise',from:['submitted','waitlisted']},{value:'request_changes',label:'Solicitar correção',from:['submitted','under_review','waitlisted']},{value:'waitlist',label:'Colocar na lista de espera',from:['submitted','under_review']},{value:'reject',label:'Indeferir inscrição',from:['submitted','under_review','waitlisted','changes_requested']},{value:'withdraw',label:'Registrar desistência',from:['draft','submitted','under_review','waitlisted','changes_requested']}].filter(item=>item.from.includes(status));
    }
    function newCampaign():void{s.tab='campaigns';s.campaignForm=emptyCampaign();s.editingCampaign=true;}
    function editCampaign(c:Campaign):void{const {id,version,slug,title,instructions,privacy_notice,terms_version,class_group_ids,opens_on,closes_on,active,require_verified_contact,require_documents,require_payment_before_enrollment,contract_template_id}=c;s.campaignForm={id,version,slug,title,instructions,privacy_notice,terms_version,class_group_ids:[...class_group_ids],opens_on,closes_on,active,require_verified_contact,require_documents,require_payment_before_enrollment,contract_template_id:contract_template_id||''};s.editingCampaign=true;}
    async function saveCampaign():Promise<void>{await run(async()=>{const {id,version,...data}=s.campaignForm;
      if(!data.class_group_ids.length)throw new Error('Selecione pelo menos uma turma para o processo.');
      if(!campaignYearId())throw new Error('Selecione turmas de um único ano letivo.');
      if(data.closes_on<data.opens_on)throw new Error('O encerramento deve ser igual ou posterior ao início.');
      if(can('documents.read')&&data.contract_template_id&&(!campaignYearId()||!eligibleContractTemplates().some(template=>template.id===data.contract_template_id)))throw new Error('Selecione um contrato ativo que exige assinatura e seja válido para o ano letivo das turmas.');
      const payload={...data,contract_template_id:data.contract_template_id||null};
      if(id)await PigeAPI.patch(base()+'/admission-campaigns/'+id,{...payload,version});else await PigeAPI.post(base()+'/admission-campaigns',payload);
      s.editingCampaign=false;await load();s.notice=data.active?'Processo salvo e publicado. O link está disponível na lista de processos.':'Processo salvo como rascunho. Publique quando estiver pronto para receber inscrições.';});}
    async function openAdmission(id:string):Promise<void>{if(s.selected?.id!==id){s.reason='';s.message='';s.internal=false;s.matchQ='';}s.selected=await PigeAPI.request<Admission>(base()+'/admissions/'+id);s.identity=false;s.studentMatches=[];s.guardianMatches=[];s.existingStudent='';s.existingGuardian='';s.contractPreview=null;s.contractValues={};s.contractPreviewStale=false;s.charges=can('banking.read')?(await PigeAPI.request<PigeOnline.Page<Charge>>(base()+'/bank-charges?admission_id='+id)).items:[];if(!admissionActions().some(item=>item.value===s.action))s.action=admissionActions()[0]?.value||'';}
    async function view(id:string):Promise<void>{await run(()=>openAdmission(id));}
    async function action():Promise<void>{await run(async()=>{const a=s.selected;if(!a)return;await PigeAPI.post(base()+'/admissions/'+a.id+'/actions',{version:a.version,action:s.action,reason:s.reason});await openAdmission(a.id);await queue();s.reason='';});}
    async function match():Promise<void>{await run(async()=>{const q=encodeURIComponent(s.matchQ);s.studentMatches=(await PigeAPI.request<PigeOnline.Page<PigeAPI.Student>>(base()+'/students?q='+q)).items;s.guardianMatches=(await PigeAPI.request<PigeOnline.Page<PigeAPI.Row>>(base()+'/persons?guardians_only=true&q='+q)).items;});}
    async function approve():Promise<void>{await run(async()=>{const a=s.selected;if(!a)return;await PigeAPI.post(base()+'/admissions/'+a.id+'/approve',{version:a.version,reason:s.reason,identity_confirmed:s.identity,existing_student_id:s.existingStudent||null,existing_guardian_id:s.existingGuardian||null});await openAdmission(a.id);await queue();s.reason='';s.notice=s.selected?.contract?.required?'Inscrição aprovada. Emita o contrato da revisão congelada e aguarde a assinatura do responsável antes de efetivar.':'Inscrição aprovada; matrícula criada como rascunho. Confira documentação e cobrança antes de efetivar.';});}
    async function finalize():Promise<void>{await run(async()=>{const a=s.selected;if(!a)return;if(a.contract?.required&&a.contract.signature_status!=='verified')throw new Error('A assinatura do responsável precisa ser conferida pela Direção antes da efetivação.');await PigeAPI.post(base()+'/admissions/'+a.id+'/finalize',{version:a.version,reason:s.reason});await openAdmission(a.id);await queue();s.reason='';s.notice='Matrícula efetivada. Comprovante disponível no portal do responsável.';});}
    async function reviewDoc(item:PigeOnline.Attachment,status:string):Promise<void>{await run(async()=>{const a=s.selected;if(!a)return;await PigeAPI.post(base()+`/admissions/${a.id}/attachments/${item.id}/review`,{version:item.version,status,note:s.reason});await openAdmission(a.id);});}
    async function message():Promise<void>{await run(async()=>{if(!s.selected)return;await PigeAPI.post(base()+'/admissions/'+s.selected.id+'/messages',{text:s.message,internal:s.internal});s.message='';await openAdmission(s.selected.id);});}
    async function whatsapp():Promise<void>{await run(async()=>{if(!s.selected)return;await PigeAPI.post(base()+'/connect/messages',{admission_id:s.selected.id,text:s.message,client_key:PigeOnline.newId()});s.message='';s.notice='Envio via WhatsApp enfileirado. Consulte o resultado na fila do WhatsApp.';});}
    async function download(path:string,name:string):Promise<void>{await run(()=>PigeAPI.download(base()+path,name));}
    function newCharge(admissionId=''):void{s.chargeForm={admission_id:admissionId,enrollment_id:'',amount:'',due_on:new Date(Date.now()+7*86400000).toISOString().slice(0,10),description:admissionId?'Matrícula':'Mensalidade',collection_mode:'manual',billing_type:'MANUAL',client_key:PigeOnline.newId(),installment_count:1,required_for_enrollment:false};s.enrollmentMatches=[];s.chargeOpen=true;s.error='';s.discardCharge=false;s.chargeInitial=JSON.stringify(s.chargeForm);if(!s.bankingStatus)void run(bankHealth);}
    function closeCharge(discard=false):void{
      if(s.busy)return;
      if(discard!==true&&JSON.stringify(s.chargeForm)!==s.chargeInitial){s.discardCharge=true;return;}
      s.chargeOpen=false;s.discardCharge=false;
    }
    function chargeTotal():string{
      const amount=Number(s.chargeForm.amount),count=Number(s.chargeForm.installment_count);
      return PigeOnline.money(Number.isFinite(amount*count)?(amount*count).toFixed(2):'0');
    }
    async function findEnrollments():Promise<void>{await run(async()=>{s.enrollmentMatches=(await PigeAPI.request<PigeOnline.Page<PigeAPI.Row>>(base()+'/enrollments?q='+encodeURIComponent(s.enrollmentQ))).items;});}
    function changeCollectionMode():void{s.chargeForm.billing_type=s.chargeForm.collection_mode==='manual'?'MANUAL':'PIX';}
    function chargeMethod(c:Charge):string{return c.collection_mode==='manual'?'Cobrança interna':c.billing_type==='PIX'?'Pix':'Boleto';}
    function chargeStatus(c:Charge):string{return c.collection_mode==='manual'&&c.status==='received_external'?'Recebido manualmente':PigeOnline.label(c.status);}
    const receiptMethods:Record<string,string>={cash:'Dinheiro',pix:'Pix recebido diretamente',transfer:'Transferência',card:'Cartão',other:'Outro'};
    function receiptDate():string{const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Bahia',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());return ['year','month','day'].map(type=>parts.find(part=>part.type===type)?.value||'').join('-');}
    async function createCharge():Promise<void>{await run(async()=>{const f=s.chargeForm;const result=await PigeAPI.post<{message:string}>(base()+'/bank-charges',{...f,admission_id:f.admission_id||null,enrollment_id:f.enrollment_id||null,installment_count:Number(f.installment_count)});s.chargeOpen=false;if(props.page==='banking')await bankList();else if(s.selected)await openAdmission(s.selected.id);s.notice=result.message;});}
    async function receiveManualCharge():Promise<void>{await run(async()=>{const charge=s.selectedCharge;if(!charge)return;const updated=await PigeAPI.post<Charge>(base()+'/bank-charges/'+charge.id+'/manual-receipt',{...s.receiptForm,version:charge.version});s.selectedCharge=updated;s.bankEvents=await PigeAPI.request<typeof s.bankEvents>(base()+'/bank-charges/'+charge.id+'/events');if(props.page==='banking')await bankList();else if(s.selected)await openAdmission(s.selected.id);s.notice='Recebimento integral registrado. O comprovante está disponível para impressão.';});}
    async function receiptPdf():Promise<void>{await run(async()=>{if(s.selectedCharge)await PigeAPI.download(base()+'/bank-charges/'+s.selectedCharge.id+'/receipt.pdf','comprovante-de-recebimento.pdf');});}
    async function inspectCharge(c:Charge):Promise<void>{await run(async()=>{const [charge,events]=await Promise.all([PigeAPI.request<Charge>(base()+'/bank-charges/'+c.id),PigeAPI.request<PigeOnline.BankEvent[]>(base()+'/bank-charges/'+c.id+'/events')]);s.selectedCharge=charge;s.bankReason='';s.bankEvents=events;s.receiptForm={amount:charge.amount,paid_on:receiptDate(),payment_method:'cash',reference:'',client_key:PigeOnline.newId()};});}
    async function chargeAction(action:string):Promise<void>{await run(async()=>{const c=s.selectedCharge;if(!c)return;await PigeAPI.post(base()+'/bank-charges/'+c.id+'/'+action,{reason:s.bankReason||(action==='sync'?'Consulta de pagamento solicitada no painel financeiro.':'')});s.selectedCharge=null;if(props.page==='banking')await bankList();else if(s.selected)await openAdmission(s.selected.id);s.notice=c.collection_mode==='manual'&&action==='cancel'?'Cobrança interna cancelada.':action==='authorize-reissue'?'Reemissão autorizada após conferência. Acompanhe a fila.':'Solicitação registrada. Aguarde o processamento e atualize a consulta.';});}
    function configure(provider:string):void{s.provider=provider;const c=s.connections.find(c=>c.provider===provider);s.connectionForm={version:c?.version,enabled:c?.enabled||false,environment:c?.environment||'sandbox',api_key:'',webhook_token:'',config:{...connectConfig(),...c?.config}};s.editingConnection=true;}
    async function saveConnection():Promise<void>{await run(async()=>{const f=s.connectionForm;await PigeAPI.post(base()+'/integrations/'+s.provider,{...f,config:s.provider==='asaas'?{}:f.config});f.api_key='';f.webhook_token='';s.editingConnection=false;await load();s.notice='Configuração salva. Teste a conexão e ative as atualizações de pagamento.';});}
    async function testConnection(provider:string):Promise<void>{await run(async()=>{const r=await PigeAPI.post<{ok:boolean;code:string;message:string}>(base()+'/integrations/'+provider+'/test',{});await load();if(!r.ok)throw new Error(bankError(r.code));s.notice=r.message;});}
    async function retry(job:PigeOnline.Job):Promise<void>{await run(async()=>{await PigeAPI.post(base()+'/integration-jobs/'+job.id+'/retry',{reason:s.reason});await jobs();});}
    async function copy(value:string):Promise<void>{await run(async()=>{await navigator.clipboard.writeText(value);s.notice='Copiado.';});}
    const connectionFor=(provider:string)=>s.connections.find(c=>c.provider===provider);
    Vue.onMounted(()=>{void run(load);});
    return {s,props,campaignSlug,campaignGroupLabel,campaignGroups,admissionActions,bankCards,bankPeriod,reconcileBank,bankError,bankOperation,activateBankWebhook,identity:PigeInstitution.state,changeCollectionMode,chargeMethod,chargeStatus,receiptMethods,receiptDate,receiveManualCharge,receiptPdf,closeCharge,chargeTotal,can,str,run,load,search,paginate,paginateJobs,newCampaign,editCampaign,saveCampaign,campaignYearId,eligibleContractTemplates,templateName,selectedContractVersion,contractStatus,contractPreviewKeys,contractFieldLabel,contractValue,contractAutomatic,setContractValue,previewFrozenContract,previewFrozenPdf,issueFrozenContract,downloadSignedContract,view,action,match,approve,finalize,reviewDoc,message,whatsapp,download,newCharge,findEnrollments,createCharge,inspectCharge,chargeAction,configure,saveConnection,testConnection,retry,copy,connectionFor,jobs,connectLoad,connectJobs,connectInventory,connectAdopt,connectAdoptNamed,connectReleaseLegacy,connectPrefer,connectPreferUnit,connectRestart,connectCreate,connectSync,connectQr,connectPairingCode,connectSavePhone,connectLogout,connectDelete,connectTest,connectRetry,clearConnectQr,label:PigeOnline.label,date:PigeOnline.date,money:PigeOnline.money,publicURL:PigeOnline.publicURL,safeLink:PigeOnline.safeLink,origin:location.origin,statuses:PigeOnline.statuses};
  }};
}
