namespace PigePortal {
  type Admission=PigeOnline.Admission;type Campaign=PigeOnline.Campaign;type Account=PigeOnline.Account;
  const state=Vue.reactive({assistSource:'',profileReadSource:'',profileOpen:false,ready:false,busy:false,error:'',notice:'',online:navigator.onLine,account:null as Account|null,campaign:null as Campaign|null,campaigns:[] as Campaign[],slug:new URLSearchParams(location.search).get('campaign')||'',mode:'login',rows:[] as Admission[],total:0,page:1,selected:null as Admission|null,editing:false,charges:[] as PigeOnline.Charge[],code:'',verifyChannel:'email',message:'',documentType:'',acceptTerms:false,legal:false,register:{name:'',email:'',password:'',cpf:'',phone:'',address:'',accept_privacy:false,whatsapp_opt_in:false},login:{email:'',password:''},reset:{email:'',code:'',password:''},form:{student:PigeOnline.person(),class_group_id:'',previous_school:'',relationship:'Responsável legal',notes:'',client_key:PigeOnline.newId()}});
  let selectedFile:File|null=null;
  async function request<T>(path:string,options:RequestInit={}):Promise<T>{
    if(!navigator.onLine)throw new Error('Sem conexão. Nenhuma matrícula é confirmada offline.');
    const headers=new Headers(options.headers);headers.set('X-CSRF-Protection','1');if(options.body&&!(options.body instanceof FormData))headers.set('Content-Type','application/json');
    const response=await fetch('/api/v1/portal'+path,{...options,headers,credentials:'same-origin',cache:'no-store'});
    if(!response.ok){let value:{detail?:string;errors?:{field:string;message:string}[]}={};try{value=await response.json();}catch{}throw new Error(value.errors?.map(x=>x.field+': '+x.message).join('\n')||value.detail||'Falha de comunicação.');}
    return await response.json() as T;
  }
  const post=<T>(path:string,value:unknown):Promise<T>=>request<T>(path,{method:'POST',body:JSON.stringify(value)});
  async function run(action:()=>Promise<void>):Promise<void>{if(state.busy)return;state.busy=true;state.error='';state.notice='';try{await action();}catch(e){state.error=e instanceof Error?e.message:String(e);}finally{state.busy=false;}}
  async function loadList():Promise<void>{const data=await request<PigeOnline.Page<Admission>>('/admissions?page='+state.page);state.rows=data.items;state.total=data.total;}
  async function loadCampaign():Promise<void>{if(state.slug){state.campaign=await request<Campaign>('/campaigns/'+encodeURIComponent(state.slug));history.replaceState({},'','/online.html?campaign='+encodeURIComponent(state.slug));}}
  async function start():Promise<void>{await run(async()=>{state.campaigns=await request<Campaign[]>('/campaigns');if(!state.slug&&state.campaigns.length===1)state.slug=state.campaigns[0].slug;await loadCampaign();try{state.account=await request<Account>('/me');await loadList();}catch{state.account=null;}});state.ready=true;}
  async function selectCampaign():Promise<void>{await run(async()=>{state.selected=null;state.editing=false;await loadCampaign();});}
  async function afterMFA(result:Record<string,unknown>):Promise<void>{state.account=result as unknown as Account;await loadList();}
  async function mfaRequest<T>(path:string,options:RequestInit={}):Promise<T>{const headers=new Headers(options.headers);headers.set('X-CSRF-Protection','1');if(options.body)headers.set('Content-Type','application/json');const r=await fetch('/api/v1'+path,{...options,headers,credentials:'same-origin',cache:'no-store'});const data=await r.json();if(!r.ok)throw new Error(data.detail||'Não foi possível confirmar a autenticação.');return data as T;}
  async function login():Promise<void>{await run(async()=>{if(!state.slug)throw new Error('Selecione o processo de matrícula.');const result=await post<Record<string,unknown>>('/login',{...state.login,campaign_slug:state.slug});state.login.password='';if(await PigeMFA.accept(result))return;await afterMFA(result);});}
  async function register():Promise<void>{await run(async()=>{if(!state.campaign)throw new Error('Selecione um processo de matrícula.');const result=await post<Record<string,unknown>>('/register',{...state.register,cpf:state.register.cpf||null,campaign_slug:state.slug,terms_version:state.campaign.terms_version});state.register.password='';if(await PigeMFA.accept(result))return;await afterMFA(result);state.notice='Conta criada. Confirme um contato e preencha os dados do aluno.';});}
  async function logout():Promise<void>{state.assistSource='';state.profileReadSource='';state.profileOpen=false;await run(async()=>{await post('/logout',{});state.account=null;state.rows=[];state.selected=null;state.charges=[];state.editing=false;state.register={name:'',email:'',password:'',cpf:'',phone:'',address:'',accept_privacy:false,whatsapp_opt_in:false};state.login.password='';state.form.student=PigeOnline.person();});}
  async function verifyRequest():Promise<void>{await run(async()=>{await post('/verification/request',{channel:state.verifyChannel});state.notice='Código solicitado. Consulte o canal escolhido; a entrega depende da integração da escola.';});}
  async function verifyConfirm():Promise<void>{await run(async()=>{state.account=await post<Account>('/verification/confirm',{code:state.code});state.code='';state.notice='Contato confirmado.';});}
  async function resetRequest():Promise<void>{await run(async()=>{await post('/password/request',{email:state.reset.email,campaign_slug:state.slug});state.notice='Caso exista uma conta elegível, o código será enviado ao e-mail informado.';});}
  async function resetConfirm():Promise<void>{await run(async()=>{await post('/password/confirm',{...state.reset,campaign_slug:state.slug});state.reset.password='';state.reset.code='';state.mode='login';state.notice='Senha redefinida. Entre novamente.';});}
  function newAdmission():void{state.assistSource='';state.error='';if(!state.campaign||!state.campaign.accepting){state.error='Selecione um processo aberto.';return;}if(state.account?.school_id!==state.campaign.school_id){state.error='Esta conta pertence a outra escola. Saia e entre no contexto correto.';return;}state.selected=null;state.form={student:PigeOnline.person(),class_group_id:'',previous_school:'',relationship:'Responsável legal',notes:'',client_key:PigeOnline.newId()};state.editing=true;}
  function edit():void{state.assistSource='';const a=state.selected;if(!a)return;const {previous_school,...student}=a.student_data;state.form={student:{...student},class_group_id:a.class_group_id,previous_school:previous_school||'',relationship:a.relationship,notes:a.notes,client_key:PigeOnline.newId()};state.editing=true;}
  async function openRecord(id:string):Promise<void>{state.assistSource='';const a=await request<Admission>('/admissions/'+id);state.selected=a;state.editing=false;state.acceptTerms=false;state.legal=false;state.charges=await request<PigeOnline.Charge[]>('/admissions/'+id+'/charges');const c=state.campaigns.find(c=>c.id===a.campaign_id);if(c&&c.slug!==state.slug){state.slug=c.slug;await loadCampaign();}state.documentType=a.document_types[0]?.id||'';}
  async function view(id:string):Promise<void>{await run(()=>openRecord(id));}
  async function save():Promise<void>{await run(async()=>{if(!state.campaign)throw new Error('Selecione um processo.');const a=state.selected;const {client_key,...body}=state.form;body.student.cpf=body.student.cpf||null;const result=a?await request<Admission>('/admissions/'+a.id,{method:'PATCH',body:JSON.stringify({...body,version:a.version})}):await post<Admission>('/admissions',{...body,campaign_id:state.campaign.id,client_key});await openRecord(result.id);await loadList();state.notice='Rascunho salvo. Envie os anexos e conclua o envio para análise.';});}
  function fileChange(e:Event):void{selectedFile=(e.target as HTMLInputElement).files?.[0]||null;}
  async function upload():Promise<void>{await run(async()=>{const a=state.selected;if(!a||!selectedFile||!state.documentType)throw new Error('Selecione o tipo e um arquivo PDF, PNG ou JPEG.');const data=new FormData();data.set('version',String(a.version));data.set('document_type_id',state.documentType);data.set('file',selectedFile);await request('/admissions/'+a.id+'/attachments',{method:'POST',body:data});selectedFile=null;await openRecord(a.id);state.notice='Documento enviado para conferência.';});}
  async function submit():Promise<void>{await run(async()=>{const a=state.selected;if(!a||!state.campaign)return;await post('/admissions/'+a.id+'/submit',{version:a.version,accept_terms:state.acceptTerms,legal_responsibility:state.legal,terms_version:state.campaign.terms_version});await openRecord(a.id);await loadList();state.notice='Inscrição enviada. Acompanhe a análise nesta página.';});}
  async function sendMessage():Promise<void>{await run(async()=>{if(!state.selected)return;await post('/admissions/'+state.selected.id+'/messages',{text:state.message});state.message='';await openRecord(state.selected.id);});}
  async function withdraw():Promise<void>{await run(async()=>{if(!state.selected||state.message.length<3)throw new Error('Descreva o motivo da desistência no campo de mensagem.');await post('/admissions/'+state.selected.id+'/withdraw',{version:state.selected.version,reason:state.message});state.message='';await openRecord(state.selected.id);await loadList();});}
  async function download(path:string,name:string):Promise<void>{await run(async()=>{const r=await fetch('/api/v1/portal'+path,{credentials:'same-origin',cache:'no-store'});if(!r.ok)throw new Error('Não foi possível baixar o documento. Recarregue a página e confira seu acesso.');const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);});}
  async function paginate(delta:number):Promise<void>{await run(async()=>{state.page+=delta;await loadList();});}
  async function refresh():Promise<void>{await run(async()=>{state.account=await request<Account>('/me');await loadList();if(state.selected)await openRecord(state.selected.id);});}
  async function copy(value:string):Promise<void>{await run(async()=>{await navigator.clipboard.writeText(value);state.notice='Código copiado. Confira o beneficiário antes de pagar.';});}
  async function saveProfile():Promise<void>{await run(async()=>{if(!state.account)return;const a=state.account;state.account=await request<Account>('/me',{method:'PATCH',body:JSON.stringify({version:a.version,name:a.name,cpf:a.cpf||null,phone:a.phone,address:a.address,whatsapp_opt_in:a.whatsapp_opt_in,...Object.fromEntries(detailFields.map(([key])=>[key,(a as unknown as Record<string,unknown>)[key]||(key==='birth_date'?null:'')]))})});state.notice='Conta atualizada. Inscrições já enviadas e cadastros oficiais não foram alterados; solicite correção à Secretaria.';});}

  const detailFields=[["birth_date", "Nascimento"], ["rg", "RG"], ["rg_issuer", "Órgão emissor"], ["birth_certificate", "Certidão"], ["mother_name", "Nome da mãe"], ["father_name", "Nome do pai"], ["postal_code", "CEP"], ["street", "Logradouro"], ["address_number", "Número"], ["address_complement", "Complemento"], ["district", "Bairro"], ["city", "Cidade"], ["state", "UF"], ["country", "País"]];
  const personAssistFields=['name','cpf','birth_date','phone','email','address',...detailFields.map(([key])=>key)];
  async function assistRequest<T>(path:string,options:RequestInit={}):Promise<T>{return request<T>(path.replace(/^\/portal/,''),options);}
  function readAttachment(id:string,who:'student'|'guardian'):void{
    if(!state.selected)return;const source='/portal/admissions/'+state.selected.id+'/attachments/'+id+'/ocr';
    if(who==='student'){edit();state.assistSource=source;}
    else{state.profileOpen=true;state.profileReadSource=source;void Vue.nextTick(()=>document.getElementById('portal-profile')?.scrollIntoView({block:'start'}));}
  }

  const editable=():boolean=>!state.selected||['draft','changes_requested'].includes(state.selected.status);
  Vue.createApp({components:{'assist-panel':PigeAssist.component},render:PigeRenders.portal,setup(){Vue.onMounted(()=>{PigeMFA.init(mfaRequest,afterMFA,logout,true);window.addEventListener('online',()=>{state.online=true;});window.addEventListener('offline',()=>{state.online=false;});if('serviceWorker'in navigator&&window.isSecureContext)void navigator.serviceWorker.register('/sw.js').catch(()=>{});void PigeInstitution.load();void start();});return {state,assistRequest,personAssistFields,detailFields,readAttachment,mfa:PigeMFA,identity:PigeInstitution.state,run,selectCampaign,login,register,logout,verifyRequest,verifyConfirm,resetRequest,resetConfirm,newAdmission,edit,view,save,fileChange,upload,submit,sendMessage,withdraw,download,paginate,refresh,copy,saveProfile,editable,label:PigeOnline.label,date:PigeOnline.date,money:PigeOnline.money,safeLink:PigeOnline.safeLink};}}).mount('#portal');
}
