"""Schema inicial da Secretaria. Snapshot imutável, não usa create_all."""
from alembic import op
import sqlalchemy as sa
revision="0001_secretary"
down_revision=None
branch_labels=None
depends_on=None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('document', sa.String(length=24), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies'))
    )
    op.create_table('installation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('configured', sa.Boolean(), nullable=False),
    sa.Column('configured_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_installation'))
    )
    op.create_table('login_attempts',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('window_started', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_login_attempts'))
    )
    op.create_table('number_sequences',
    sa.Column('key', sa.String(length=160), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_number_sequences'))
    )
    op.create_table('users',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("role IN ('admin','secretary','viewer')", name=op.f('ck_users_valid_role')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('auth_sessions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_sessions'))
    )
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('schools',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('address', sa.String(length=400), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('document_policy', sa.String(length=16), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("document_policy IN ('warn','block')", name=op.f('ck_schools_document_policy')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_schools_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schools'))
    )
    op.create_table('academic_years',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('ends_on >= starts_on', name=op.f('ck_academic_years_year_dates')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_academic_years_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_academic_years')),
    sa.UniqueConstraint('school_id', 'name', name=op.f('uq_academic_years_school_id'))
    )
    op.create_index(op.f('ix_academic_years_school_id'), 'academic_years', ['school_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('school_id', sa.String(length=36), nullable=True),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_events_actor_id_users')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_audit_events_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index(op.f('ix_audit_events_school_id'), 'audit_events', ['school_id'], unique=False)
    op.create_table('files',
    sa.Column('original_name', sa.String(length=240), nullable=False),
    sa.Column('storage_key', sa.String(length=200), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_files_created_by_users')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_files_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_files')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_files_storage_key'))
    )
    op.create_index(op.f('ix_files_school_id'), 'files', ['school_id'], unique=False)
    op.create_table('grades',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('level', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_grades_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grades')),
    sa.UniqueConstraint('school_id', 'name', name=op.f('uq_grades_school_id'))
    )
    op.create_index(op.f('ix_grades_school_id'), 'grades', ['school_id'], unique=False)
    op.create_table('persons',
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('social_name', sa.String(length=180), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('address', sa.String(length=400), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('is_guardian', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_persons_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_persons')),
    sa.UniqueConstraint('school_id', 'cpf', name=op.f('uq_persons_school_id'))
    )
    op.create_index(op.f('ix_persons_name'), 'persons', ['name'], unique=False)
    op.create_index(op.f('ix_persons_school_id'), 'persons', ['school_id'], unique=False)
    op.create_table('school_access',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_school_access_school_id_schools')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_school_access_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'school_id', name=op.f('pk_school_access'))
    )
    op.create_table('shifts',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_shifts_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shifts')),
    sa.UniqueConstraint('school_id', 'name', name=op.f('uq_shifts_school_id'))
    )
    op.create_index(op.f('ix_shifts_school_id'), 'shifts', ['school_id'], unique=False)
    op.create_table('units',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_units_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_units')),
    sa.UniqueConstraint('school_id', 'name', name=op.f('uq_units_school_id'))
    )
    op.create_index(op.f('ix_units_school_id'), 'units', ['school_id'], unique=False)
    op.create_table('class_groups',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('unit_id', sa.String(length=36), nullable=False),
    sa.Column('academic_year_id', sa.String(length=36), nullable=False),
    sa.Column('grade_id', sa.String(length=36), nullable=False),
    sa.Column('shift_id', sa.String(length=36), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('capacity > 0', name=op.f('ck_class_groups_positive_capacity')),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], name=op.f('fk_class_groups_academic_year_id_academic_years')),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], name=op.f('fk_class_groups_grade_id_grades')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_class_groups_school_id_schools')),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name=op.f('fk_class_groups_shift_id_shifts')),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], name=op.f('fk_class_groups_unit_id_units')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_class_groups')),
    sa.UniqueConstraint('school_id', 'academic_year_id', 'unit_id', 'name', name=op.f('uq_class_groups_school_id'))
    )
    op.create_index(op.f('ix_class_groups_school_id'), 'class_groups', ['school_id'], unique=False)
    op.create_table('document_types',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('grade_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], name=op.f('fk_document_types_grade_id_grades')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_document_types_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_types')),
    sa.UniqueConstraint('school_id', 'name', name=op.f('uq_document_types_school_id'))
    )
    op.create_index(op.f('ix_document_types_school_id'), 'document_types', ['school_id'], unique=False)
    op.create_table('students',
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('previous_school', sa.String(length=180), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_students_person_id_persons')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_students_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_students')),
    sa.UniqueConstraint('person_id', name=op.f('uq_students_person_id')),
    sa.UniqueConstraint('school_id', 'number', name=op.f('uq_students_school_id'))
    )
    op.create_index(op.f('ix_students_school_id'), 'students', ['school_id'], unique=False)
    op.create_table('enrollments',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('academic_year_id', sa.String(length=36), nullable=False),
    sa.Column('class_group_id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('enrolled_on', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('financial_person_id', sa.String(length=36), nullable=True),
    sa.Column('previous_enrollment_id', sa.String(length=36), nullable=True),
    sa.Column('activation_key', sa.String(length=160), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.CheckConstraint("status IN ('draft','active','suspended','transferred','cancelled','completed')", name=op.f('ck_enrollments_enrollment_status')),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], name=op.f('fk_enrollments_academic_year_id_academic_years')),
    sa.ForeignKeyConstraint(['class_group_id'], ['class_groups.id'], name=op.f('fk_enrollments_class_group_id_class_groups')),
    sa.ForeignKeyConstraint(['financial_person_id'], ['persons.id'], name=op.f('fk_enrollments_financial_person_id_persons')),
    sa.ForeignKeyConstraint(['previous_enrollment_id'], ['enrollments.id'], name=op.f('fk_enrollments_previous_enrollment_id_enrollments')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_enrollments_school_id_schools')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_enrollments_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrollments')),
    sa.UniqueConstraint('activation_key', name=op.f('uq_enrollments_activation_key')),
    sa.UniqueConstraint('school_id', 'number', name=op.f('uq_enrollments_school_id'))
    )
    op.create_index(op.f('ix_enrollments_school_id'), 'enrollments', ['school_id'], unique=False)
    op.create_index(op.f('ix_enrollments_student_id'), 'enrollments', ['student_id'], unique=False)
    op.create_table('protocols',
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('due_on', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_protocols_school_id_schools')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_protocols_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_protocols')),
    sa.UniqueConstraint('school_id', 'number', name=op.f('uq_protocols_school_id'))
    )
    op.create_index(op.f('ix_protocols_school_id'), 'protocols', ['school_id'], unique=False)
    op.create_table('student_documents',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('document_type_id', sa.String(length=36), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('validated_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.CheckConstraint("status IN ('received','validated','rejected','waived','archived')", name=op.f('ck_student_documents_document_status')),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], name=op.f('fk_student_documents_document_type_id_document_types')),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_student_documents_file_id_files')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_student_documents_school_id_schools')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_student_documents_student_id_students')),
    sa.ForeignKeyConstraint(['validated_by'], ['users.id'], name=op.f('fk_student_documents_validated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_documents'))
    )
    op.create_index(op.f('ix_student_documents_school_id'), 'student_documents', ['school_id'], unique=False)
    op.create_index(op.f('ix_student_documents_student_id'), 'student_documents', ['student_id'], unique=False)
    op.create_table('student_guardians',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('relationship', sa.String(length=60), nullable=False),
    sa.Column('legal', sa.Boolean(), nullable=False),
    sa.Column('financial', sa.Boolean(), nullable=False),
    sa.Column('pickup', sa.Boolean(), nullable=False),
    sa.Column('primary_contact', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_student_guardians_person_id_persons')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_student_guardians_school_id_schools')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_student_guardians_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_guardians')),
    sa.UniqueConstraint('student_id', 'person_id', name=op.f('uq_student_guardians_student_id'))
    )
    op.create_index(op.f('ix_student_guardians_school_id'), 'student_guardians', ['school_id'], unique=False)
    op.create_index(op.f('ix_student_guardians_student_id'), 'student_guardians', ['student_id'], unique=False)
    op.create_table('enrollment_events',
    sa.Column('enrollment_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('before', sa.JSON(), nullable=False),
    sa.Column('after', sa.JSON(), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_enrollment_events_actor_id_users')),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], name=op.f('fk_enrollment_events_enrollment_id_enrollments')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_enrollment_events_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrollment_events'))
    )
    op.create_index(op.f('ix_enrollment_events_enrollment_id'), 'enrollment_events', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_enrollment_events_school_id'), 'enrollment_events', ['school_id'], unique=False)
    op.create_table('issued_documents',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('enrollment_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=False),
    sa.Column('template_version', sa.String(length=20), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_issued_documents_created_by_users')),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], name=op.f('fk_issued_documents_enrollment_id_enrollments')),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_issued_documents_file_id_files')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_issued_documents_school_id_schools')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_issued_documents_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issued_documents'))
    )
    op.create_index(op.f('ix_issued_documents_school_id'), 'issued_documents', ['school_id'], unique=False)
    op.create_index(op.f('ix_issued_documents_student_id'), 'issued_documents', ['student_id'], unique=False)
    # ### end Alembic commands ###
    op.execute(sa.text("INSERT INTO installation (id, configured) VALUES (1, false)"))
    if op.get_bind().dialect.name == 'postgresql':
        op.execute(sa.text("CREATE FUNCTION prevent_audit_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Audit log is append-only'; END; $$"))
        op.execute(sa.text("CREATE TRIGGER audit_immutable BEFORE UPDATE OR DELETE ON audit_events FOR EACH ROW EXECUTE FUNCTION prevent_audit_mutation()"))
    elif op.get_bind().dialect.name == 'sqlite':
        op.execute(sa.text("CREATE TRIGGER audit_no_update BEFORE UPDATE ON audit_events BEGIN SELECT RAISE(ABORT, 'Audit log is append-only'); END"))
        op.execute(sa.text("CREATE TRIGGER audit_no_delete BEFORE DELETE ON audit_events BEGIN SELECT RAISE(ABORT, 'Audit log is append-only'); END"))


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issued_documents_student_id'), table_name='issued_documents')
    op.drop_index(op.f('ix_issued_documents_school_id'), table_name='issued_documents')
    op.drop_table('issued_documents')
    op.drop_index(op.f('ix_enrollment_events_school_id'), table_name='enrollment_events')
    op.drop_index(op.f('ix_enrollment_events_enrollment_id'), table_name='enrollment_events')
    op.drop_table('enrollment_events')
    op.drop_index(op.f('ix_student_guardians_student_id'), table_name='student_guardians')
    op.drop_index(op.f('ix_student_guardians_school_id'), table_name='student_guardians')
    op.drop_table('student_guardians')
    op.drop_index(op.f('ix_student_documents_student_id'), table_name='student_documents')
    op.drop_index(op.f('ix_student_documents_school_id'), table_name='student_documents')
    op.drop_table('student_documents')
    op.drop_index(op.f('ix_protocols_school_id'), table_name='protocols')
    op.drop_table('protocols')
    op.drop_index(op.f('ix_enrollments_student_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_school_id'), table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_students_school_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_document_types_school_id'), table_name='document_types')
    op.drop_table('document_types')
    op.drop_index(op.f('ix_class_groups_school_id'), table_name='class_groups')
    op.drop_table('class_groups')
    op.drop_index(op.f('ix_units_school_id'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_shifts_school_id'), table_name='shifts')
    op.drop_table('shifts')
    op.drop_table('school_access')
    op.drop_index(op.f('ix_persons_school_id'), table_name='persons')
    op.drop_index(op.f('ix_persons_name'), table_name='persons')
    op.drop_table('persons')
    op.drop_index(op.f('ix_grades_school_id'), table_name='grades')
    op.drop_table('grades')
    op.drop_index(op.f('ix_files_school_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_audit_events_school_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_academic_years_school_id'), table_name='academic_years')
    op.drop_table('academic_years')
    op.drop_table('schools')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_table('users')
    op.drop_table('number_sequences')
    op.drop_table('login_attempts')
    op.drop_table('installation')
    op.drop_table('companies')
    # ### end Alembic commands ###
    if op.get_bind().dialect.name == "postgresql":
        op.execute(sa.text("DROP FUNCTION IF EXISTS prevent_audit_mutation()"))
