"""portal_admissions_banking_integrations"""
from alembic import op
import sqlalchemy as sa

revision = '0003_online_admissions'
down_revision = '0002_protocol_events'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admission_campaigns',
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('privacy_notice', sa.Text(), nullable=False),
    sa.Column('terms_version', sa.String(length=40), nullable=False),
    sa.Column('class_group_ids', sa.JSON(), nullable=False),
    sa.Column('opens_on', sa.Date(), nullable=False),
    sa.Column('closes_on', sa.Date(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('require_verified_contact', sa.Boolean(), nullable=False),
    sa.Column('require_documents', sa.Boolean(), nullable=False),
    sa.Column('require_payment_before_enrollment', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('closes_on >= opens_on', name=op.f('ck_admission_campaigns_campaign_dates')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_admission_campaigns_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admission_campaigns')),
    sa.UniqueConstraint('slug', name=op.f('uq_admission_campaigns_slug'))
    )
    op.create_index(op.f('ix_admission_campaigns_school_id'), 'admission_campaigns', ['school_id'], unique=False)
    op.create_table('integration_connections',
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('environment', sa.String(length=16), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('encrypted_secrets', sa.Text(), nullable=False),
    sa.Column('last_test_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_test_ok', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.CheckConstraint("provider IN ('connect_api','asaas')", name=op.f('ck_integration_connections_integration_provider')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_integration_connections_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integration_connections')),
    sa.UniqueConstraint('school_id', 'provider', name=op.f('uq_integration_connections_school_id'))
    )
    op.create_index(op.f('ix_integration_connections_school_id'), 'integration_connections', ['school_id'], unique=False)
    op.create_table('portal_accounts',
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('phone', sa.String(length=24), nullable=False),
    sa.Column('address', sa.String(length=400), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('whatsapp_opt_in', sa.Boolean(), nullable=False),
    sa.Column('registration_consent', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_portal_accounts_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portal_accounts')),
    sa.UniqueConstraint('school_id', 'email', name=op.f('uq_portal_accounts_school_id'))
    )
    op.create_index(op.f('ix_portal_accounts_school_id'), 'portal_accounts', ['school_id'], unique=False)
    op.create_table('integration_jobs',
    sa.Column('connection_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('dedupe_key', sa.String(length=180), nullable=False),
    sa.Column('encrypted_payload', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=False),
    sa.Column('remote_id', sa.String(length=160), nullable=False),
    sa.Column('delivery_status', sa.String(length=32), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['integration_connections.id'], name=op.f('fk_integration_jobs_connection_id_integration_connections')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_integration_jobs_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integration_jobs')),
    sa.UniqueConstraint('dedupe_key', name=op.f('uq_integration_jobs_dedupe_key'))
    )
    op.create_index(op.f('ix_integration_jobs_school_id'), 'integration_jobs', ['school_id'], unique=False)
    op.create_index(op.f('ix_integration_jobs_status'), 'integration_jobs', ['status'], unique=False)
    op.create_table('integration_webhooks',
    sa.Column('connection_id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=200), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('remote_id', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['integration_connections.id'], name=op.f('fk_integration_webhooks_connection_id_integration_connections')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_integration_webhooks_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integration_webhooks')),
    sa.UniqueConstraint('connection_id', 'event_id', name=op.f('uq_integration_webhooks_connection_id'))
    )
    op.create_index(op.f('ix_integration_webhooks_school_id'), 'integration_webhooks', ['school_id'], unique=False)
    op.create_table('portal_challenges',
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('purpose', sa.String(length=24), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['portal_accounts.id'], name=op.f('fk_portal_challenges_account_id_portal_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portal_challenges'))
    )
    op.create_index(op.f('ix_portal_challenges_account_id'), 'portal_challenges', ['account_id'], unique=False)
    op.create_table('portal_sessions',
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['portal_accounts.id'], name=op.f('fk_portal_sessions_account_id_portal_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portal_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_portal_sessions_token_hash'))
    )
    op.create_index(op.f('ix_portal_sessions_account_id'), 'portal_sessions', ['account_id'], unique=False)
    op.create_table('admissions',
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('client_key', sa.String(length=80), nullable=False),
    sa.Column('class_group_id', sa.String(length=36), nullable=False),
    sa.Column('student_data', sa.JSON(), nullable=False),
    sa.Column('guardian_snapshot', sa.JSON(), nullable=False),
    sa.Column('relationship', sa.String(length=60), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('consent', sa.JSON(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('student_id', sa.String(length=36), nullable=True),
    sa.Column('enrollment_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.CheckConstraint("status IN ('draft','submitted','under_review','changes_requested','waitlisted','approved','enrolled','rejected','withdrawn')", name=op.f('ck_admissions_admission_status')),
    sa.ForeignKeyConstraint(['account_id'], ['portal_accounts.id'], name=op.f('fk_admissions_account_id_portal_accounts')),
    sa.ForeignKeyConstraint(['campaign_id'], ['admission_campaigns.id'], name=op.f('fk_admissions_campaign_id_admission_campaigns')),
    sa.ForeignKeyConstraint(['class_group_id'], ['class_groups.id'], name=op.f('fk_admissions_class_group_id_class_groups')),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], name=op.f('fk_admissions_enrollment_id_enrollments')),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_admissions_reviewed_by_users')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_admissions_school_id_schools')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_admissions_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admissions')),
    sa.UniqueConstraint('account_id', 'client_key', name=op.f('uq_admissions_account_id')),
    sa.UniqueConstraint('enrollment_id', name=op.f('uq_admissions_enrollment_id')),
    sa.UniqueConstraint('school_id', 'number', name=op.f('uq_admissions_school_id'))
    )
    op.create_index(op.f('ix_admissions_account_id'), 'admissions', ['account_id'], unique=False)
    op.create_index(op.f('ix_admissions_campaign_id'), 'admissions', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_admissions_school_id'), 'admissions', ['school_id'], unique=False)
    op.create_table('admission_attachments',
    sa.Column('admission_id', sa.String(length=36), nullable=False),
    sa.Column('document_type_id', sa.String(length=36), nullable=False),
    sa.Column('original_name', sa.String(length=240), nullable=False),
    sa.Column('storage_key', sa.String(length=200), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('review_note', sa.Text(), nullable=False),
    sa.Column('student_document_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], name=op.f('fk_admission_attachments_admission_id_admissions')),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], name=op.f('fk_admission_attachments_document_type_id_document_types')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_admission_attachments_school_id_schools')),
    sa.ForeignKeyConstraint(['student_document_id'], ['student_documents.id'], name=op.f('fk_admission_attachments_student_document_id_student_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admission_attachments')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_admission_attachments_storage_key'))
    )
    op.create_index(op.f('ix_admission_attachments_admission_id'), 'admission_attachments', ['admission_id'], unique=False)
    op.create_index(op.f('ix_admission_attachments_school_id'), 'admission_attachments', ['school_id'], unique=False)
    op.create_table('admission_messages',
    sa.Column('admission_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('internal', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['portal_accounts.id'], name=op.f('fk_admission_messages_account_id_portal_accounts')),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_admission_messages_actor_id_users')),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], name=op.f('fk_admission_messages_admission_id_admissions')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_admission_messages_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admission_messages'))
    )
    op.create_index(op.f('ix_admission_messages_admission_id'), 'admission_messages', ['admission_id'], unique=False)
    op.create_index(op.f('ix_admission_messages_school_id'), 'admission_messages', ['school_id'], unique=False)
    op.create_table('bank_charges',
    sa.Column('connection_id', sa.String(length=36), nullable=False),
    sa.Column('admission_id', sa.String(length=36), nullable=True),
    sa.Column('enrollment_id', sa.String(length=36), nullable=True),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('payer_snapshot', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('due_on', sa.Date(), nullable=False),
    sa.Column('billing_type', sa.String(length=16), nullable=False),
    sa.Column('required_for_enrollment', sa.Boolean(), nullable=False),
    sa.Column('external_reference', sa.String(length=160), nullable=False),
    sa.Column('client_key', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('remote_customer_id', sa.String(length=160), nullable=False),
    sa.Column('remote_payment_id', sa.String(length=160), nullable=True),
    sa.Column('customer_attempted', sa.Boolean(), nullable=False),
    sa.Column('payment_attempted', sa.Boolean(), nullable=False),
    sa.Column('invoice_url', sa.Text(), nullable=False),
    sa.Column('bank_slip_url', sa.Text(), nullable=False),
    sa.Column('pix_copy_paste', sa.Text(), nullable=False),
    sa.Column('pix_image', sa.Text(), nullable=False),
    sa.Column('pix_expires_at', sa.String(length=60), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.CheckConstraint("billing_type IN ('PIX','BOLETO')", name=op.f('ck_bank_charges_charge_type')),
    sa.CheckConstraint('amount > 0', name=op.f('ck_bank_charges_charge_amount')),
    sa.ForeignKeyConstraint(['account_id'], ['portal_accounts.id'], name=op.f('fk_bank_charges_account_id_portal_accounts')),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], name=op.f('fk_bank_charges_admission_id_admissions')),
    sa.ForeignKeyConstraint(['connection_id'], ['integration_connections.id'], name=op.f('fk_bank_charges_connection_id_integration_connections')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_bank_charges_created_by_users')),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], name=op.f('fk_bank_charges_enrollment_id_enrollments')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_bank_charges_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bank_charges')),
    sa.UniqueConstraint('connection_id', 'remote_payment_id', name=op.f('uq_bank_charges_connection_id')),
    sa.UniqueConstraint('external_reference', name=op.f('uq_bank_charges_external_reference')),
    sa.UniqueConstraint('school_id', 'client_key', name=op.f('uq_bank_charges_school_id'))
    )
    op.create_index(op.f('ix_bank_charges_admission_id'), 'bank_charges', ['admission_id'], unique=False)
    op.create_index(op.f('ix_bank_charges_enrollment_id'), 'bank_charges', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_bank_charges_school_id'), 'bank_charges', ['school_id'], unique=False)
    op.create_index(op.f('ix_bank_charges_status'), 'bank_charges', ['status'], unique=False)
    op.create_table('bank_events',
    sa.Column('charge_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('previous_status', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['charge_id'], ['bank_charges.id'], name=op.f('fk_bank_events_charge_id_bank_charges')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_bank_events_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bank_events'))
    )
    op.create_index(op.f('ix_bank_events_charge_id'), 'bank_events', ['charge_id'], unique=False)
    op.create_index(op.f('ix_bank_events_school_id'), 'bank_events', ['school_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bank_events_school_id'), table_name='bank_events')
    op.drop_index(op.f('ix_bank_events_charge_id'), table_name='bank_events')
    op.drop_table('bank_events')
    op.drop_index(op.f('ix_bank_charges_status'), table_name='bank_charges')
    op.drop_index(op.f('ix_bank_charges_school_id'), table_name='bank_charges')
    op.drop_index(op.f('ix_bank_charges_enrollment_id'), table_name='bank_charges')
    op.drop_index(op.f('ix_bank_charges_admission_id'), table_name='bank_charges')
    op.drop_table('bank_charges')
    op.drop_index(op.f('ix_admission_messages_school_id'), table_name='admission_messages')
    op.drop_index(op.f('ix_admission_messages_admission_id'), table_name='admission_messages')
    op.drop_table('admission_messages')
    op.drop_index(op.f('ix_admission_attachments_school_id'), table_name='admission_attachments')
    op.drop_index(op.f('ix_admission_attachments_admission_id'), table_name='admission_attachments')
    op.drop_table('admission_attachments')
    op.drop_index(op.f('ix_admissions_school_id'), table_name='admissions')
    op.drop_index(op.f('ix_admissions_campaign_id'), table_name='admissions')
    op.drop_index(op.f('ix_admissions_account_id'), table_name='admissions')
    op.drop_table('admissions')
    op.drop_index(op.f('ix_portal_sessions_account_id'), table_name='portal_sessions')
    op.drop_table('portal_sessions')
    op.drop_index(op.f('ix_portal_challenges_account_id'), table_name='portal_challenges')
    op.drop_table('portal_challenges')
    op.drop_index(op.f('ix_integration_webhooks_school_id'), table_name='integration_webhooks')
    op.drop_table('integration_webhooks')
    op.drop_index(op.f('ix_integration_jobs_status'), table_name='integration_jobs')
    op.drop_index(op.f('ix_integration_jobs_school_id'), table_name='integration_jobs')
    op.drop_table('integration_jobs')
    op.drop_index(op.f('ix_portal_accounts_school_id'), table_name='portal_accounts')
    op.drop_table('portal_accounts')
    op.drop_index(op.f('ix_integration_connections_school_id'), table_name='integration_connections')
    op.drop_table('integration_connections')
    op.drop_index(op.f('ix_admission_campaigns_school_id'), table_name='admission_campaigns')
    op.drop_table('admission_campaigns')
    # ### end Alembic commands ###
